ory/hydra

- README.md
> update accounts CLI Usage

- cli/hydra-host/handler/account.go
latest gopass returns multiple values for GetPasswd
> handle multiple return values from gopass

- README.md
"What it looks like", not "how it looks like"
(Very common mistake)
> Fix idiom in README

- cmd/server/handler.go
> Mount warden handler

- client/handler.go
- client/manager_memory.go
- client/manager_rethinkdb.go
- client/manager_test.go
- cmd/server/handler_client_factory.go
- cmd/token_self.go
- glide.lock
- oauth2/consent_strategy.go
- oauth2/oauth2_auth_code_test.go
- oauth2/oauth2_test.go
> client: return client secret on POST and remove it from GET

- README.md
By reading the installation, I was a little bit confused by all the
available options. I attempted to split a little bit the installation
paragraph to make it more clear.
> Add some precisions to installation

- cmd/server/handler_connection_factory.go
- cmd/token_user.go
- sdk/client.go
* closes #141
* closes #137
* closes #138
> all: resolve issues with the sdk and cli

- README.md
Minor README tweaks. I tried to keep everything in the spirit of what exists.
> doc: Minor grammar/spelling fixes for README

- README.md
> readme: Fix table of contents links

- cmd/cli/handler_client.go
Signed-off-by: Matt Vinall <boyvinall@gmail.com>
> ensure client endpoint is initialised for CLI "clients import" command

- client/manager.go
- client/manager_http.go
- client/manager_memory.go
- client/manager_rethinkdb.go
fix for #150
Signed-off-by: Matt Vinall <boyvinall@gmail.com>
> client: fix client.GetClients() for multiple clients

- client/manager_memory.go
- client/manager_rethinkdb.go
- client/manager_test.go
- cmd/server/handler_connection_factory.go
- connection/manager.go
- connection/manager_http.go
- connection/manager_memory.go
- connection/manager_rethinkdb.go
- connection/manager_test.go
- glide.lock
- internal/fosite_store_memory.go
- internal/fosite_store_rethinkdb.go
- jwk/manager_memory.go
- jwk/manager_rethinkdb.go
> all: add test cases for methods returning slices or maps of entities

- cmd/host.go
> Fix #274 - replace HYDRA_PROFILING with PROFILING

- client/manager_redis.go
- client/manager_test.go
- cmd/host.go
- cmd/server/handler_client_factory.go
- cmd/server/handler_jwk_factory.go
- cmd/server/handler_oauth2_factory.go
- config/backend_connections.go
- config/config.go
- docker-compose.yml
- glide.lock
- glide.yaml
- jwk/manager_redis.go
- jwk/manager_test.go
- oauth2/fosite_store_redis.go
- oauth2/fosite_store_test.go
Commits for https://github.com/ory-am/hydra/issues/306
> store/redis: redis backend for hydra

- cmd/host.go
Noticed this as I was installing it - not a big deal but worth correcting for accuracy.
> Small typo.

- docs/tutorial.md
updating bash command in tutorial to `/bin/sh`
> Update bash command in tutorial

- docs/oauth2.md
> Remove uname references from docs

- herodot/json.go
> herodot: resolve issue with infinite loop caused by certain error chain

- glide.lock
- glide.yaml
> vendor: upgrade fosite to resolve regression issue

- docs/security.md
> ✏️  minor grammar typo

- oauth2/consent_strategy.go
- oauth2/handler.go
This PR adds Key ID to the JWT header of the ID token.
Signed-off-by: pbarker <pbarker@datapipe.com>
> Add Key Id to Header

- policy/handler.go
Fixes listing policies https://github.com/ory/hydra/issues/458
Signed-off-by: pbarker <pbarker@datapipe.com>
> Policy Fix

- config/backend_connections.go
- config/backend_connections_test.go
> config: remove sql control parameters from dsn before connecting

- config/backend_connections.go
> config: connect to cleaned DSN

- cmd/server/handler.go
> cmd/server: resolve gorilla session mem leak - closes #461

- docs/api.swagger.yaml
- warden/group/handler.go
Fixes swagger for warden group member operations
> Fix Swagger for Warden Groups

- cmd/policies_create.go
> cmd/policies: description is a string field, not slice

- jwk/handler.go
> jwk/handler: nest ac check and resolve stray log message

- pkg/errors.go
> pkg/errors: make ErrNotFound return a status code

- oauth2/handler.go
- oauth2/introspector_test.go
> oauth2/introspect: send issuer in introspection

- cmd/server/handler_oauth2_factory.go
- docs/oauth2.md
- glide.lock
- glide.yaml
- oauth2/handler.go
> oauth2: allow redirection to client if consent was denied

- glide.lock
- glide.yaml
> oauth2/introspect>: resolve 401 on invalid token

- docs/SUMMARY.md
- docs/faq/migrations.md
> docs: add FAQ on missing migrate in docker image

- .gitignore
- Dockerfile
- Dockerfile-automigrate
- Dockerfile-demo
- Dockerfile-http
- Dockerfile-without-telemetry
- client/manager_test.go
- cmd/root.go
- cmd/server/handler_client_factory.go
- cmd/server/handler_jwk_factory.go
- cmd/server/handler_oauth2_factory.go
- config/backend_memory.go
- config/backend_plugin.go
- config/backend_sql.go
- config/backend_sql_test.go
- config/config.go
- glide.lock
Warning: This feature is experimental and undocumented.
> Db plugin connector

- cmd/server/handler_health_factory.go
- docs/api.swagger.yaml
- health/doc.go
- health/handler.go
> cmd/host: move status info to dedicated endpoint

- client/handler.go
- glide.lock
- glide.yaml
- pkg/secret.go
> oauth2: form-urldecode authorization basic header

- glide.lock
- glide.yaml
Signed-off-by: Olivier Deckers <deckers.olivier@gmail.com>
Before creating your pull request, make sure that you have
[signed the DOC](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md#developers-certificate-of-origin). You can ammend your
signature to the current commit using `git commit --amend -s`.
Please create PRs only for bugs, or features that have been discussed with the maintainers, either at the
[ORY Community](https://community.ory.am/) or join the [ORY Chat](https://gitter.im/ory-am/hydra).
> Update to ladon 0.8.2

- .travis.yml
- glide.lock
Resolves build issue on windows and closes #571
> vendor: update various dependencies

- cmd/cli/handler_policy.go
Fix for issue: https://github.com/ory/hydra/issues/583
Signed-off-by: Lukasz Jagiello <jagiello.lukasz@gmail.com>
> cmd/cli: typo Connection -> Policy

- docs/oauth2.md
links for apiary didn't link to correct section of the page as the # was incorrect.
> updated links to apiary as the old ones didn't work

- docs/install.md
Signed-off-by: Dallan Quass <dallan@quass.org>
Before creating your pull request, make sure that you have
[signed the DOC](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md#developers-certificate-of-origin). You can ammend your
signature to the current commit using `git commit --amend -s`.
Please create PRs only for bugs, or features that have been discussed with the maintainers, either at the
[ORY Community](https://community.ory.am/) or join the [ORY Chat](https://gitter.im/ory-am/hydra).
> fix health link in docs

- Gopkg.lock
- cmd/host.go
- cmd/server/handler.go
> cmd: Added cors support to host process

- config/config.go
- docs/telemetry.md
- metrics/middleware.go
- metrics/middleware_test.go
> telemetry: Update telemetry identification

- client/client.go
- docs/api.swagger.json
Signed-off-by: Philip Nicolcev <phil.nicolcev@tulip.io>
> docs: Make space optional in scope regex (#661)

- doc.go
- docs/api.swagger.json
- sdk/go/hydra/swagger/README.md
- sdk/go/hydra/swagger/docs/Handler.md
- sdk/go/hydra/swagger/handler.go
- sdk/js/swagger/README.md
- sdk/js/swagger/docs/Handler.md
- sdk/js/swagger/src/model/Handler.js
- warden/group/handler.go
> groups: Corrects group scope documentation

- sdk/go/hydra/sdk.go
> sdk/go: Resolves incorrect error message

- cmd/token_client.go
> cmd: Makes scopes in token command configurable

- docker-compose.yml
- docs/install.md
- docs/tutorial.md
> docs: Resolves issue with broken 5-minute tutorial

- composer.json
> sdk: Adds php registry dummy

- cmd/cli/handler_client.go
- cmd/cli/handler_groups.go
- cmd/cli/handler_introspection.go
- cmd/cli/handler_jwk.go
- cmd/cli/handler_policy.go
- cmd/cli/handler_recovation.go
- config/config.go
> add a save way to get the ClusterURL and append to it

- client/handler.go
> client: Returns 404 only when policy allows getting a client

- cmd/server/handler.go
- config/config.go
- metrics/metrics.go
- metrics/middleware.go
> metrics: Improves naming of traits

- consent/strategy_default.go
> consent: Always bust auth session if remember is false

- Gopkg.lock
- Gopkg.toml
> oauth2: Rejects requests without nonce in implicit/hybrid

- oauth2/handler.go
> oauth2: Ignores JTI in userinfo

- Gopkg.lock
- Gopkg.toml
> vendor: Upgrades fosite dependency

- .circleci/config.yml
- .npmignore
- docker-compose.yml
- scripts/run-deploy.sh
This patch (hopefully) improves issues with the Circle-CI toolchain.
> ci: Improves build toolchain

- cmd/cli/handler_migrate.go
- cmd/server/handler_consent_factory.go
- consent/doc.go
- consent/handler.go
- consent/manager.go
- consent/manager_memory.go
- consent/manager_sql.go
- consent/manager_test.go
- consent/sdk_test.go
- consent/strategy_default_test.go
- docs/api.swagger.json
- integration/sql_schema_test.go
- oauth2/fosite_store_memory.go
- oauth2/handler.go
- oauth2/oauth2_auth_code_test.go
- sdk/go/hydra/swagger/README.md
- sdk/go/hydra/swagger/docs/OAuth2Api.md
- sdk/go/hydra/swagger/o_auth2_api.go
- sdk/js/swagger/README.md
- sdk/js/swagger/docs/OAuth2Api.md
- sdk/js/swagger/src/api/OAuth2Api.js
- sdk/php/swagger/README.md
- sdk/php/swagger/docs/Api/OAuth2Api.md
- sdk/php/swagger/lib/Api/OAuth2Api.php
> consent: Adds ability to revoke consent and login sessions

- cmd/server/handler.go
- cmd/server/handler_client_factory.go
- cmd/server/handler_consent_factory.go
- cmd/server/handler_health_factory.go
- cmd/server/handler_jwk_factory.go
- cmd/server/handler_oauth2_factory.go
- cmd/server/helper_cert.go
- cmd/server/helper_deps.go
- cmd/server/helper_keys.go
> cmd: Check dependencies are defined before instantiation

- Gopkg.lock
- Gopkg.toml
- MAINTAINERS
> oauth2: Improve token endpoint authentication error message

- package.json
yarn / npm otherwise give a warning
Signed-off-by: Jan Beckmann <king-jan1999@hotmail.de>
> Use spdx expression for license in package.json

- .dockerignore
> docker: Update .dockerignore

- cmd/server/handler_oauth2_factory.go
- jwk/jwt_strategy.go
- oauth2/handler.go
- oauth2/handler_struct.go
> oauth2: Refactor JWT strategy

- consent/handler.go
- consent/manager_memory.go
- consent/manager_sql.go
- consent/manager_test.go
- consent/strategy_default.go
> consent: Return proper error when no consent was found

- Gopkg.lock
- Gopkg.toml
> vendor: Upgrade sqlcon to 0.0.5

- cmd/server/handler_oauth2_factory.go
- oauth2/handler.go
- oauth2/handler_struct.go
> oauth2: Share error details with redirect fallback

- sdk/go/hydra/sdk_api.go
I am not shure the DOC signature made it into this one
> consent: Add ListUserConsentSessions to OAuth2API interface

- client/manager_memory.go
> client: Improve memory manager error messages

- cmd/server/handler_oauth2_factory.go
> cmd: Public subject type should cause public id alg

- sdk/go/hydra/sdk_api.go
> sdk: Add new methods to SDK interface

- cmd/server/banner.go
- cmd/server/handler.go
Close #987
Signed-off-by: arekkas <aeneas@ory.am>
> cmd: Add version to banner

- Dockerfile
- Dockerfile-alpine
Signed-off-by: Dmitry Budaev <condemil@gmail.com>
> Fix serve all cmd in docker files

- cmd/server/handler.go
Signed-off-by: aeneasr <aeneas.rekkas@serlo.org>
> cmd: Use viper for cors detection

- Gopkg.lock
- Gopkg.toml
- cmd/server/handler_oauth2_factory.go
- cmd/server/helper_cors.go
- oauth2/introspector_test.go
- oauth2/oauth2_helper_test.go
- oauth2/revocator_test.go
> cmd: Replace aeneasr/cors with rs/cors

- cmd/cli/handler_migrate.go
- cmd/migrate.go
- cmd/migrate_secret.go
- cmd/root.go
- config/config.go
- jwk/manager_sql.go
- jwk/manager_test.go
> jwk: Add ability to rotate SYSTEM_SECRET 

- config/config.go
> cmd: Clarify HYDRA_ADMIN_URL in missing endpoint message

- Gopkg.lock
- Gopkg.toml
- consent/strategy_default.go
- consent/strategy_default_test.go
> oauth2: Accept expired JWTs as id_token_hint

- consent/handler.go
Signed-off-by: Prateek Malhotra <someone1@gmail.com>
> consent: Add SessionsPath const

- Gopkg.lock
- Gopkg.toml
- consent/strategy_default.go
Signed-off-by: Prateek Malhotra <someone1@gmail.com>
> fosite: bump to version 0.24.0 with associated code changes

- Gopkg.lock
- Gopkg.toml
- sdk/go/hydra/swagger/api_client.go
Signed-off-by: Pierre-David Bélanger <pierredavidbelanger@gmail.com>
This is what we talked about in #1063
`go test ./...` is all `ok`
> change go-resty import path for gopkg.in/resty.v1

- rand/sequence/sequence_test.go
> rand: Fix flaky random test

- UPGRADE.md
> Add schema changes introduced to UPGRADE.md

- cmd/server/handler.go
- cmd/server/handler_jwk_factory.go
- jwk/handler.go
- jwk/handler_test.go
- jwk/sdk_test.go
/.wellknown/jwks.json also need to handle cors.
force push.
> jwks: cors for wellknown endpoints

- .circleci/config.yml
- cmd/server/handler_oauth2_factory.go
- cmd/token_user.go
- config/config.go
> ci: Check vet and fix vet errors

- cmd/server/handler_oauth2_factory.go
> server: Instantiate PKCE after oidc

- consent/handler.go
- consent/manager_sql.go
> consent: Only fetch latest consent state 

- jwk/manager_0_sql_migrations_test.go
> Minor bug fix in JWK sql migrations test case

- cmd/token_user.go
> cmd: Improve token user error handling

- cmd/cli/handler_migrate.go
- cmd/root_test.go
> cmd: Resolve panic in migration handler

- cmd/serve.go
- cmd/server/handler.go
> cmd: Improve issuer error message

- cmd/server/handler_jwk_factory.go
- cmd/server/handler_oauth2_factory.go
- cmd/server/helper_cors.go
- cmd/server/helper_cors_test.go
- go.mod
- go.sum
Resolves an issue where wildcards would incorrectly be used as literal strings.
Closes #1073
> cmd: Resolve broken wildcard cors

- client/handler.go
- client/sql_migration_files.go
- consent/handler.go
- consent/sql_migration_files.go
- health/doc.go
- jwk/handler.go
- oauth2/handler.go
> sdk: Update swagger endpoint definition

- go.mod
- go.sum
> vendor: Upgrade to fosite 0.27.4

- README.md
Previous link was 404.
force push.
> Fixed tutorial link in README.md

- consent/handler.go
- consent/manager.go
- consent/manager_memory.go
- consent/manager_sql.go
- consent/manager_test_helpers.go
- consent/strategy_default.go
Instead of just showing consent requests which have remember set to true, show all past consent request.
Closes #1203
> consent: Show all granted consent requests

- cmd/cli/handler_migrate.go
> Set ROTATED_SYSTEM_SECRET to old secret as speficied in docs.

- README.md
- go.mod
- go.sum
Fix old information at README.
`hydra serve all` is available instead of `hydra host` to run with in-memory database.
force push.
> docs: Update docs how to serve with in memory database

- config/config.go
- config/config_test.go
- go.mod
- go.sum
#1282 
Check not only remote IP bu also `X-Forwarded-For` header when enabled TLS termination option.
force push.
> config: Support multi proxies between TLS termination proxy and hydra

- .circleci/config.yml
- Dockerfile
- Dockerfile-alpine
- go.mod
- go.sum
Just bump golang to 1.12.0
https://golang.org/doc/go1.12
force push.
> docker: Bump golang to 1.12.0

- .circleci/config.yml
> circleci: disable modules support temporarily when fetching a tool

- Dockerfile
- Dockerfile-alpine
Bump golang tp 1.12.1.
This is minor update.
https://golang.org/doc/devel/release.html#go1.12.minor
force push.
> docker: Bump Golang to 1.12.1

- .circleci/config.yml
> ci: Use oryOS naming topology for docker release

- .goreleaser.yml
> ci: Remove pure git tag from docker release

- cmd/server/handler.go
- driver/driver.go
- driver/driver_default.go
- driver/registry.go
- driver/registry_base.go
Resolves issues with lazy loading. Closes #1349
> driver: Initialize everything on start up

- cmd/cli/handler_helper.go
- cmd/clients.go
- cmd/keys.go
- cmd/token.go
- go.mod
- go.sum
> cmd: Add resilience to CLI REST commands

- README.md
Now contributors link refers to 404 (https://github.com/ory/hydra/blob/master/graphs/contributors).
force push.
> README.md: Fix contributors link

- consent/strategy_default.go
- consent/strategy_default_test.go
- go.mod
- go.sum
> consent: Allow prompt=none for public clients

- docs/config.yaml
Viper is looking for ttl at the top-level. Update these docs to reflect reality.
> ttl is a top-level config value

- consent/handler.go
- consent/manager_memory.go
- consent/strategy_default.go
- consent/strategy_default_test.go
- oauth2/oauth2_auth_code_test.go
Resolves a regression issue introduced by OpenID Connect Front/Back-Channel Logout.
Closes #1409
Signed-off-by: Saad Tazi <stazi@fruitsoftware.com>
force push.
> consent: Do not confirmLoginSession when skip is true (#1414)

- driver/configuration/provider_viper.go
- driver/configuration/provider_viper_test.go
- jwk/handler.go
- jwk/handler_test.go
> config: Remove duplicates JWKS IDs from wellknown config

- cmd/serve.go
- docs/config.yaml
- driver/configuration/provider_viper.go
- driver/configuration/provider_viper_test.go
- driver/cors_test.go
- go.mod
- go.sum
> cors: Use sane default settings for CORS options

- composer.json
> Fixed composer namespace

- go.mod
- go.sum
> mod: Update ory/x to 0.0.63

- docs/config.yaml
> Fixed typoe. Not -c but --config

- cmd/serve.go
Fix a minor mistake in command name given in help docs
> Fix wrong command name

- README.md
Some community projects are outdated and haven seen any love in the last years. Marking them helps others to navigate faster through the docs. 
> Update libraries and 3rd parties section

- README.md
> doc: Add adopters placeholder

- doc.go
- oauth2/handler.go
> Improve OAuth2 API Docs

- go.mod
> #1539 FIXED

- docs/config.yaml
This PR is just to remove confusing config value for dsn.
> chore: remove confusing dsn setting value

- quickstart-prometheus-config.yml
- quickstart-prometheus.yml
I add an quickstart for Prometheus, and add want to add it to 5min-tutorial.
I also create another [PR for doc](https://github.com/ory/docs/pull/202).
> Add quickstart for prometheus.

- .circleci/config.yml
- cmd/cli/handler_migrate.go
- cmd/tools.go
- go.mod
- go.sum
> cli: Resolve Go 1.12.7 regression in migrate sql

- go.mod
- go.sum
> oauth2: Enable PKCE for private clients

- client/handler.go
- client/manager.go
- client/manager_memory.go
- client/manager_sql.go
- client/manager_test_helpers.go
- oauth2/fosite_store_memory.go
- oauth2/fosite_store_sql.go
> clients: Ensure order of paginated results

- .goreleaser.yml
- Dockerfile-alpine
- oauth2/fosite_store_memory.go
- oauth2/fosite_store_sql.go
> docker: Add alpine image

- docs/config.yaml
- driver/configuration/provider.go
- driver/configuration/provider_viper.go
- driver/registry_base.go
#1577
Add in the oauth2.pkce.enforce part of the configuration file.
> Make EnforcePKCE confurable

- driver/driver_default.go
Closes https://github.com/ory/k8s/issues/55
> cmd: Remove stray log lines

- client/manager_sql.go
#1595 
Changed PK from int to int64, ran `make test` with no issues. 
> client: change pk field to int64

- UPGRADE.md
> Update upgrade changelog

- oauth2/handler.go
... (and generated documentation)
> Fix typo in handler.go comment

- go.mod
- go.sum
https://github.com/ory/hydra/issues/1642
@aeneasr 
> Bump fosite to v0.30.2

- cmd/helper.go
- cmd/helper_test.go
As discussed with @aeneasr on discord, here are some test cases to improve coverage.
I have added a test case for `fatal()` helper fn.
> cmd: Added tests for helpers

- Dockerfile-alpine
> Create and use a proper user in the alpine Dockerfile

- .circleci/config.yml
> Use circleci changelog orb

- Dockerfile
- Dockerfile-alpine
- Dockerfile-e2e
None
Bump docker base images
Go to v1.13.5
Alpine to v3.11
> docker: Bump docker base images

- go.mod
- go.sum
- [ x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
- [x ] I have read the [security policy](../security/policy)
- [x ] I confirm that this pull request does not address a security vulnerability. If this pull request addresses a security
> updated x module

- README.md
Just to keep the README consistent, made 2 small punctuation changes.
> Small punctuation README change

- CONTRIBUTING.md
- README.md
- SECURITY.md
> docs: Updates issue and pull request templates

- consent/helper.go
- consent/strategy_default.go
- docs/config.yaml
- driver/configuration/provider.go
- driver/configuration/provider_viper.go
- driver/configuration/provider_viper_test.go
Recent changes to Chrome require setting of SameSite cookie policy if it is acceptable for cookies to be used in a third party setting: https://blog.chromium.org/2020/02/samesite-cookie-changes-in-february.html
Some discussion on this in the community board https://community.ory.sh/t/does-hydra-support-samesite-none-for-cookies/1491
> feat: New setting to specify SameSite cookie mode

- consent/x_manager_sql_migrations_test.go
> fix: Add failing test case for #1725

- client/handler.go
- docs/api.swagger.json
- internal/httpclient/client/admin/get_o_auth2_client_responses.go
> fix(client): Remove 404 from GET responses

- docs/api.swagger.json
- internal/httpclient/models/accept_consent_request.go
- internal/httpclient/models/completed_request.go
- internal/httpclient/models/consent_request.go
- internal/httpclient/models/consent_request_session.go
- internal/httpclient/models/flush_inactive_o_auth2_tokens_request.go
- internal/httpclient/models/health_not_ready_status.go
- internal/httpclient/models/health_status.go
- internal/httpclient/models/json_web_key.go
- internal/httpclient/models/json_web_key_set_generator_request.go
- internal/httpclient/models/login_request.go
- internal/httpclient/models/o_auth2_client.go
- internal/httpclient/models/o_auth2_token_introspection.go
- internal/httpclient/models/oauth2_token_response.go
- internal/httpclient/models/open_id_connect_context.go
- internal/httpclient/models/previous_consent_session.go
- internal/httpclient/models/reject_request.go
- internal/httpclient/models/userinfo_response.go
- internal/httpclient/models/version.go
- internal/httpclient/models/well_known.go
- test/e2e/Dockerfile-e2e-env
> chore: bump e2e image to Go 1.14

- go.mod
- go.sum
> chore: bump github.com/ory/fosite to v0.30.5

- docs/api.swagger.json
- internal/httpclient/models/accept_login_request.go
- internal/httpclient/models/completed_request.go
- internal/httpclient/models/consent_request.go
- internal/httpclient/models/consent_request_session.go
- internal/httpclient/models/flush_inactive_o_auth2_tokens_request.go
- internal/httpclient/models/generic_error.go
- internal/httpclient/models/health_status.go
- internal/httpclient/models/json_web_key.go
- internal/httpclient/models/json_web_key_set.go
- internal/httpclient/models/json_web_key_set_generator_request.go
- internal/httpclient/models/login_request.go
- internal/httpclient/models/logout_request.go
- internal/httpclient/models/o_auth2_client.go
- internal/httpclient/models/o_auth2_token_introspection.go
- internal/httpclient/models/oauth2_token_response.go
- internal/httpclient/models/open_id_connect_context.go
- internal/httpclient/models/previous_consent_session.go
- internal/httpclient/models/reject_request.go
- internal/httpclient/models/userinfo_response.go
- internal/httpclient/models/well_known.go
- oauth2/fosite_store_helpers.go
> fix: add forgotten error check to test

- docs/scripts/fix-api.js
- docs/scripts/rerelease.js
- docs/src/pages/versions.js
> chore: update docusaurus template

- README.md
Fix link to new docs URL at README
> fix: Link to docs at README

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/support.md
- .github/PULL_REQUEST_TEMPLATE.md
- .schema/api.swagger.json
- CONTRIBUTING.md
- README.md
- SECURITY.md
- internal/httpclient/models/accept_consent_request.go
- internal/httpclient/models/completed_request.go
- internal/httpclient/models/consent_request_session.go
- internal/httpclient/models/flush_inactive_o_auth2_tokens_request.go
- internal/httpclient/models/generic_error.go
- internal/httpclient/models/health_not_ready_status.go
- internal/httpclient/models/health_status.go
- internal/httpclient/models/json_web_key_set.go
- internal/httpclient/models/json_web_key_set_generator_request.go
- internal/httpclient/models/login_request.go
- internal/httpclient/models/logout_request.go
- internal/httpclient/models/o_auth2_client.go
- internal/httpclient/models/o_auth2_token_introspection.go
- internal/httpclient/models/oauth2_token_response.go
- internal/httpclient/models/previous_consent_session.go
- internal/httpclient/models/reject_request.go
- internal/httpclient/models/userinfo_response.go
- internal/httpclient/models/version.go
- internal/httpclient/models/well_known.go
> docs: update github templates

- .schema/api.swagger.json
- .schema/config.schema.json
- cmd/root.go
- cmd/server/helper_cert.go
- driver/configuration/provider_viper.go
- driver/configuration/provider_viper_test.go
- internal/.hydra.yaml
- internal/driver.go
- internal/httpclient/models/accept_consent_request.go
- internal/httpclient/models/completed_request.go
- internal/httpclient/models/consent_request.go
- internal/httpclient/models/consent_request_session.go
- internal/httpclient/models/flush_inactive_o_auth2_tokens_request.go
- internal/httpclient/models/generic_error.go
- internal/httpclient/models/health_not_ready_status.go
- internal/httpclient/models/health_status.go
- internal/httpclient/models/json_web_key.go
- internal/httpclient/models/json_web_key_set.go
- internal/httpclient/models/logout_request.go
- internal/httpclient/models/o_auth2_client.go
- internal/httpclient/models/oauth2_token_response.go
- internal/httpclient/models/open_id_connect_context.go
- internal/httpclient/models/previous_consent_session.go
- internal/httpclient/models/userinfo_response.go
- internal/httpclient/models/version.go
- internal/httpclient/models/well_known.go
closes #1804 
This pr fixes 6 bugs in the config.schema.json and adds `"additionalProperties": false` where appropriate.
> fix: resolve bugs in config schema

- docs/docs/install.md
> docs: update linux install guide

- .circleci/config.yml
- .goreleaser.yml
- .schema/api.swagger.json
- docs/config.js
- internal/httpclient/models/accept_consent_request.go
- internal/httpclient/models/consent_request_session.go
- internal/httpclient/models/flush_inactive_o_auth2_tokens_request.go
- internal/httpclient/models/generic_error.go
- internal/httpclient/models/health_not_ready_status.go
- internal/httpclient/models/health_status.go
- internal/httpclient/models/json_web_key.go
- internal/httpclient/models/json_web_key_set.go
- internal/httpclient/models/json_web_key_set_generator_request.go
- internal/httpclient/models/logout_request.go
- internal/httpclient/models/o_auth2_client.go
- internal/httpclient/models/o_auth2_token_introspection.go
- internal/httpclient/models/oauth2_token_response.go
- internal/httpclient/models/previous_consent_session.go
- internal/httpclient/models/reject_request.go
- internal/httpclient/models/userinfo_response.go
- internal/httpclient/models/version.go
- internal/httpclient/models/well_known.go
> ci: dry e2e test config

- docs/docs/debugging.mdx
> docs: add CSRF section to debug

- docs/versioned_docs/version-v1.4/sdk/index.md
> Fixed two broken links

- .schema/api.swagger.json
- driver/registry_base.go
- internal/httpclient/models/accept_consent_request.go
- internal/httpclient/models/accept_login_request.go
- internal/httpclient/models/completed_request.go
- internal/httpclient/models/consent_request.go
- internal/httpclient/models/consent_request_session.go
- internal/httpclient/models/flush_inactive_o_auth2_tokens_request.go
- internal/httpclient/models/generic_error.go
- internal/httpclient/models/health_status.go
- internal/httpclient/models/json_web_key.go
- internal/httpclient/models/json_web_key_set.go
- internal/httpclient/models/json_web_key_set_generator_request.go
- internal/httpclient/models/login_request.go
- internal/httpclient/models/o_auth2_client.go
- internal/httpclient/models/o_auth2_token_introspection.go
- internal/httpclient/models/oauth2_token_response.go
- internal/httpclient/models/open_id_connect_context.go
- internal/httpclient/models/previous_consent_session.go
- internal/httpclient/models/reject_request.go
- internal/httpclient/models/userinfo_response.go
- internal/httpclient/models/version.go
- internal/httpclient/models/well_known.go
> fix: improve system secrets message

- .circleci/config.yml
- .schema/api.swagger.json
- internal/httpclient/models/accept_login_request.go
- internal/httpclient/models/completed_request.go
- internal/httpclient/models/consent_request.go
- internal/httpclient/models/consent_request_session.go
- internal/httpclient/models/flush_inactive_o_auth2_tokens_request.go
- internal/httpclient/models/health_not_ready_status.go
- internal/httpclient/models/json_web_key.go
- internal/httpclient/models/json_web_key_set.go
- internal/httpclient/models/json_web_key_set_generator_request.go
- internal/httpclient/models/login_request.go
- internal/httpclient/models/logout_request.go
- internal/httpclient/models/o_auth2_client.go
- internal/httpclient/models/oauth2_token_response.go
- internal/httpclient/models/open_id_connect_context.go
- internal/httpclient/models/previous_consent_session.go
- internal/httpclient/models/reject_request.go
- internal/httpclient/models/userinfo_response.go
- internal/httpclient/models/version.go
> ci: bump changelog task

- docs/docs/advanced.md
> docs: add tls self-signed certificate guide

- .schema/api.swagger.json
- docs/docs/5min-tutorial.mdx
- docs/versioned_docs/version-1.4/5min-tutorial.mdx
- docs/versioned_docs/version-v1.4/5min-tutorial.mdx
- internal/httpclient/models/accept_consent_request.go
- internal/httpclient/models/accept_login_request.go
- internal/httpclient/models/completed_request.go
- internal/httpclient/models/consent_request.go
- internal/httpclient/models/consent_request_session.go
- internal/httpclient/models/flush_inactive_o_auth2_tokens_request.go
- internal/httpclient/models/generic_error.go
- internal/httpclient/models/json_web_key.go
- internal/httpclient/models/json_web_key_set.go
- internal/httpclient/models/json_web_key_set_generator_request.go
- internal/httpclient/models/login_request.go
- internal/httpclient/models/logout_request.go
- internal/httpclient/models/o_auth2_token_introspection.go
- internal/httpclient/models/oauth2_token_response.go
- internal/httpclient/models/open_id_connect_context.go
- internal/httpclient/models/previous_consent_session.go
- internal/httpclient/models/reject_request.go
- internal/httpclient/models/userinfo_response.go
- internal/httpclient/models/well_known.go
Before these links would lead relatively to `https://www.ory.sh/hydra/docs/127.0.0.1:16686/search`
> fix(docs): prefix href to jaeger tracing ui with http://

- .schema/api.swagger.json
- consent/handler.go
- internal/httpclient/client/admin/admin_client.go
- internal/httpclient/client/admin/list_subject_consent_sessions_responses.go
- internal/httpclient/models/accept_consent_request.go
- internal/httpclient/models/accept_login_request.go
- internal/httpclient/models/completed_request.go
- internal/httpclient/models/consent_request.go
- internal/httpclient/models/consent_request_session.go
- internal/httpclient/models/flush_inactive_o_auth2_tokens_request.go
- internal/httpclient/models/generic_error.go
- internal/httpclient/models/health_not_ready_status.go
- internal/httpclient/models/health_status.go
- internal/httpclient/models/login_request.go
- internal/httpclient/models/o_auth2_client.go
- internal/httpclient/models/o_auth2_token_introspection.go
- internal/httpclient/models/oauth2_token_response.go
- internal/httpclient/models/plugin_config_network.go
- internal/httpclient/models/plugin_config_rootfs.go
- internal/httpclient/models/plugin_env.go
- internal/httpclient/models/plugin_settings.go
- internal/httpclient/models/previous_consent_session.go
- internal/httpclient/models/userinfo_response.go
- internal/httpclient/models/version.go
- internal/httpclient/models/volume_usage_data.go
- internal/httpclient/models/well_known.go
Closes #1856
the changes.
works.
> docs: clarify consent request list endpoint

- driver/configuration/provider_viper.go
- driver/configuration/provider_viper_test.go
Fixes #1866
Just add `offline_access` to discovery supported scoped.
the changes.
works.
> fix: Add offline_access to discovery supported scoped

- docs/docs/sdk.md
- docs/sidebar.js
> docs: move sdk to top level directory

- .schema/config.schema.json
- docs/docs/reference/configuration.md
- internal/.hydra.yaml
Configure for `log.leak_sensitive_values`
https://github.com/ory/x/blob/1d71d8e0ecd975a517cc8e6adac564f08601a523/logrusx/logrus.go#L131-L132
the changes.
works.
> chore: Configure for log.leak_sensitive_values

- consent/handler.go
> fix: properly return when subject is empty

- go.mod
- go.sum
> chore: bump fosite to 0.32.2

- .circleci/config.yml
- .nancy-ignore
- go.mod
- go.sum
> Bump ci orbs

- consent/types_test.go
> fix: use correct assertion in test

- cmd/token_user.go
the changes.
- [N/A ] I have added tests that prove my fix is effective or that my feature
works.
- [N/A] I have added or changed [the documentation](docs/docs).
> fix: remove duplicate html tags

- docs/docs/guides/ssl-https-tls.mdx
- docs/versioned_docs/version-v1.6/guides/ssl-https-tls.mdx
> docs: Update ssl-https-tls.mdx: the example needs to quote strings not spawn a subshell

- docs/docs/concepts/before-oauth2.mdx
- docs/docs/concepts/oauth2.mdx
- docs/sidebar.js
> docs: add section on oauth2 limitations at beginning

- docs/docs/concepts/before-oauth2.mdx
> docs: fixed a few typos

- docs/sidebar.js
Added token-expiration to sidebar.
the changes.
works.
> docs: added sidebar item

- docs/docs/sdk/go.md
> docs: add sdk samples for tls termination and tls verify skip

- docs/docs/configure-deploy.mdx
Not 100% sure it works like this but the link should point to `hydra/docs/5-minute-tutorial/` not `hydra/docs/configure-deploy/hydra/5min-tutorial.md`
the changes.
works.
> docs: fixed link

- .circleci/config.yml
- Makefile
- cmd/clidoc/main.go
- cmd/root.go
- cmd/server/handler.go
- docs/sidebar.json
- driver/cors.go
- driver/cors_test.go
- go.mod
- go.sum
> docs: add and automate CLI docs markdown generator

- doc.go
- docs/docs/case-study.md
- docs/docs/concepts/oauth2.mdx
- docs/docs/reference/api.mdx
- docs/docs/sdk.md
- docs/docusaurus.config.js
- docs/versioned_docs/version-v1.4/5min-tutorial.mdx
- docs/versioned_docs/version-v1.4/case-study.md
- docs/versioned_docs/version-v1.4/configure-deploy.mdx
- docs/versioned_docs/version-v1.4/reference/api.md
- docs/versioned_docs/version-v1.4/sdk/index.md
- docs/versioned_docs/version-v1.5/5min-tutorial.mdx
- docs/versioned_docs/version-v1.5/case-study.md
- docs/versioned_docs/version-v1.5/configure-deploy.mdx
- docs/versioned_docs/version-v1.5/reference/api.mdx
- docs/versioned_docs/version-v1.5/sdk.md
- docs/versioned_docs/version-v1.6/5min-tutorial.mdx
- docs/versioned_docs/version-v1.6/case-study.md
- docs/versioned_docs/version-v1.6/concepts/oauth2.mdx
- docs/versioned_docs/version-v1.6/configure-deploy.mdx
- docs/versioned_docs/version-v1.6/reference/api.mdx
- docs/versioned_docs/version-v1.6/sdk.md
> docs: fix broken links

- UPGRADE.md
This stemmed from a conversation in Slack [here](https://ory-community.slack.com/archives/C012RBW0F18/p1596623043096200?thread_ts=1596497355.081600&cid=C012RBW0F18).
Add 1.5 notes to UPGRADING.md
the changes.
works.
> docs: Add 1.5 notes to UPGRADING.md

- .nancy-ignore
> ci: fix etcd CVEs

- oauth2/handler.go
> docs: remove introspect security spec

- README.md
- internal/httpclient/client/admin/admin_client.go
added a go pkg badge from here:
https://pkg.go.dev/badge/
the changes.
works.
> docs: Update README.md

- docs/versioned_docs/version-v1.7/guides/consent.mdx
> fix spelling

- cmd/cli/handler_introspection.go
- cmd/token_introspect.go
- docs/docs/5min-tutorial.mdx
- docs/docs/cli/hydra-token-introspect.md
- oauth2/introspector_test.go
- test/mock-client/main.go
> Deprecate client flags in introspect

- docs/versioned_docs/version-v1.7/debug.mdx
@aeneasr 
Update docs
the changes.
works.
> docs: add note about refresh token invalidation

- client/handler.go
- consent/handler.go
#2015 
Started to change the capitalization. Is it correct and should I continue?
the changes.
works. **⚠️ Not sure about this.**
I'm willing to change all files if the format is okay with you otherwise just let me know. It's also my first PR so I hope I did everything correct.
> NYT style capitalization

- README.md
Updated repository templates to https://github.com/ory/meta/commit/1d3bdaf243c166ab2ed8a6de1c33ca728ff620a3.
> chore: update repository template to 1d3bdaf2

- docs/docs/guides/consent.mdx
- docs/docs/guides/login.mdx
- docs/docs/guides/logout.mdx
s̶i̶g̶n̶l̶e̶ ̶p̶a̶g̶e̶ ̶a̶p̶p̶  ➡️  single page app
the changes.
works.
> docs: fix typo

- cmd/cli/handler_client.go
- cmd/clients_update.go
- docs/docs/cli/hydra-clients-update.md
- docs/docs/cli/hydra-clients.md
- docs/sidebar.json
#2020 
Add client update command in CLI.
the changes.
works.
Only if you pass the `secret` flag, the client secret will be updated and returned.
The same strategy as the API.
> feat: add client update command in CLI

- consent/strategy_default.go
- consent/strategy_default_test.go
- oauth2/handler.go
#1993 
- [x ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ x] I have read the [security policy](../security/policy).
- [ x] I confirm that this pull request does not address a security
the changes.
- [x ] I have added tests that prove my fix is effective or that my feature
works.
> feat: Support POST method for Logout

- docs/docs/guides/consent.mdx
None, it's just a tiny docs change
Currently, the link to the consent flow documentation in [Implementing the Consent Endpoint & UI](https://www.ory.sh/hydra/docs/guides/consent/) points to [https://www.ory.sh/hydra/docs/guides/concepts/consent](https://www.ory.sh/hydra/docs/guides/concepts/consent) which is just one level to deep (right path: [https://www.ory.sh/hydra/docs/concepts/consent/](https://www.ory.sh/hydra/docs/concepts/consent/).
This PR changes the link.
*(Note: I just noticed that this actually works sometimes, at least in Firefox, which is kind of strange?!)*
the changes.
- [-] I …
> docs: Fix relative path in consent flow doc

- README.md
Updated repository templates to https://github.com/ory/meta/commit/c83480b9a03610c31c0a6bc4819f645e5c05b00f.
> chore: update repository template to c83480b9

- docs/docs/concepts/login.mdx
Adds a missing word.
the changes.
works.
> docs: Adds missing word in documentation sentence

- README.md
Updated repository templates to https://github.com/ory/meta/commit/ddb4d3dedae5de26fb5db83fabf491fe58735e67.
> chore: update repository template to ddb4d3de

- go.mod
- go.sum
- internal/httpclient/client/admin/admin_client.go
> fix: bump ory/fosite to v0.34.1 to address CVEs

- .github/workflows/closed_references.yml
- .github/workflows/labels.yml
- .github/workflows/milestone.yml
- .github/workflows/stale.yml
- internal/httpclient/client/admin/admin_client.go
Updated repository templates to https://github.com/ory/meta/commit/7900d6c75a8a6e5f583591d5110eacacda1ef286.
> chore: update repository template to 7900d6c7

- docs/docs/5min-tutorial.mdx
corrected the port from 5 minute example.
This is the response you get:
```
Setting up home route on http://127.0.0.1:5555/
Setting up callback listener on http://127.0.0.1:5555/callback
Press ctrl + c on Linux / Windows or cmd + c on OSX to end the process.
If your browser does not open automatically, navigate to:
http://127.0.0.1:5555/
```
the changes.
works.
> docs: correct port

- .goreleaser.yml
- .nancy-ignore
- go.mod
- go_mod_indirect_pins.go
closes #2116 
closes #2115 
closes #2117 
closes #2111 
the changes.
works.
> fix: resolve several reference issues

- .schema/api.swagger.json
- internal/httpclient/client/admin/admin_client.go
- metrics/prometheus/doc.go
- oauth2/handler.go
These should be the last places, therefore closes #2015
> docs: swagger route headline capitalization

- README.md
Changes link for kubernetes helm chart from closed pull request to ory.sh helm chart documentation.
the changes.
works.
> docs: updates kubernetes helm chart url

- .circleci/config.yml
> chore(deps): bump cci orbs

- consent/strategy_default_test.go
The merge request does not relate to any issue, just remove unused variable in tests.
The merge request does not propose any change.
the changes.
works.
> test: remove unused expectSession variable

- docs/config.js
- docs/docs/install.md
- docs/versioned_docs/version-v1.4/install.md
- docs/versioned_docs/version-v1.5/install.md
- docs/versioned_docs/version-v1.6/install.md
- docs/versioned_docs/version-v1.7/install.md
- docs/versioned_docs/version-v1.8/install.md
- docs/versioned_docs/version-v1.9/install.md
- quickstart-cockroach.yml
- quickstart-mysql.yml
- quickstart-postgres.yml
> Improve auto docs versioning

- .goreleaser.yml
> fix: force brew install statement

- docs/sidebar.json
- oauth2/oauth2_client_credentials_test.go
@zepatrik fyi
the changes.
works.
> test: fix misused id field

- README.md
Closes #2154
the changes.
works.
> docs: deps are installed automagically and make deps was removed

- docs/docs/concepts/consent.mdx
> docs: minor improvements to the concepts/consent page

- .schema/config.schema.json
- docs/scripts/config.js
Added short explanation to config.js
Added maximum values to config.schema.json
Is there some way I can test building the config?
the changes.
works.
> docs: bcrypt reference config

- docs/docs/concepts/consent.mdx
small corrections on the documentation of consent flow but which improves consistency
the changes.
works.
> docs: fix omissions in consent flow description

- docs/docs/5min-tutorial.mdx
- docs/versioned_docs/version-v1.8/5min-tutorial.mdx
Added the new Quickstart video to version 1.8 and next.
the changes.
> docs: add quickstart video

- docs/docs/configure-deploy.mdx
> docs: add note about mounting the config file when using docker

- docs/docs/configure-deploy.mdx
- docs/versioned_docs/version-v1.9/configure-deploy.mdx
- oauth2/handler_fallback_endpoints.go
> docs: OAUTH2_ERROR_URL -> URLS_ERROR

- client/doc.go
- client/handler.go
Issue `#2267`
Adding doc on upper bound  on 500 clients
the changes.
works.
> Issue #2267 Document upper bound on limit parameter

- docs/config.js
- docs/docs/install.md
- docs/versioned_docs/version-v1.9/install.md
> Resolve various documentation issues

- .schema/config.schema.json
Closes #2270
the changes.
works.
> fix: update schema reference for subject_identifiers.supported_types

- docs/docs/faq.md
Added two items to the FAQ that were sitting in meta/tmp.
the changes.
works.
> docs: add faq items

- docs/docs/concepts/before-oauth2.mdx
- docs/versioned_docs/version-v1.9/concepts/before-oauth2.mdx
as discussed in
https://github.com/ory/hydra/pull/2295
closes https://github.com/ory/hydra/pull/2295
the changes.
works.
> docs: update before oauth2.mdx

- docs/docs/guides/logout.mdx
- docs/docs/sdk/js.md
- docs/versioned_docs/version-v1.4/sdk/index.md
- docs/versioned_docs/version-v1.9/guides/login.mdx
- docs/versioned_docs/version-v1.9/guides/logout.mdx
- docs/versioned_docs/version-v1.9/sdk/js.md
as discussed: https://ory-community.slack.com/archives/C012RBW0F18/p1610690128004100
changed js npm from
@oryd/hydra-client to
@ory/hydra-client
the changes.
works.
> docs: fix js npm

- docs/docs/5min-tutorial.mdx
The error message does not show up anymore when doing the Quickstart. 
Next I will be adding config as proposed here: https://github.com/ory/hydra/discussions/2315#discussioncomment-305943
the changes.
works.
> docs: remove unused error msg

- docs/docs/faq.md
- docs/versioned_docs/version-v1.9/faq.md
> docs: faq custom data

- .schema/config.schema.json
Updated wrong config schema values
the changes.
works.
> fix: Update config.schema.json

- CONTRIBUTING.md
- docs/docs/contributing.md
- internal/httpclient/client/admin/admin_client.go
- internal/httpclient/client/public/public_client.go
Updated repository templates to https://github.com/ory/meta/commit/9c9e465a1a1c06e4fe353464672c9069f1f11f49.
> chore: update repository template to 9c9e465a

- docs/docs/guides/oauth2-token-introspection.mdx
- docs/versioned_docs/version-v1.9/guides/oauth2-token-introspection.mdx
> docs: fix link

- .circleci/config.yml
> ci: add trailing slash to prettier check

- .circleci/config.yml
> ci: use nancy command instead of job

- .circleci/config.yml
- cypress.json
- test/e2e/circle-ci.bash
> ci: run e2e tests in one container

- .circleci/config.yml
- .gitignore
- cypress.json
- internal/httpclient/models/volume.go
- spec/api.json
- test/e2e/circle-ci.bash
> ci: link to cypress project

- README.md
- internal/httpclient/client/admin/revoke_authentication_session_responses.go
- internal/httpclient/client/admin/revoke_consent_sessions_responses.go
- internal/httpclient/models/plugin_config_interface.go
- spec/api.json
Updated repository templates to https://github.com/ory/meta/commit/1e38ec4e626751a13ecd6f35c1aef2517c88dd65.
> chore: update repository template to 1e38ec4e

- .circleci/config.yml
- cypress/helpers/index.js
- cypress/integration/oauth2/authorize_error.js
- cypress/integration/oauth2/client_creds.js
- cypress/integration/openid/logout.js
- cypress/integration/openid/prompt.js
- cypress/support/commands.js
- go.mod
- internal/httpclient/models/plugin_config_interface.go
- internal/httpclient/models/volume.go
- spec/api.json
- test/e2e/circle-ci.bash
> test: resolve flaky cypress tests

- .circleci/config.yml
- .schema/version.schema.json
- go.mod
- internal/httpclient/models/plugin_config_interface.go
- spec/api.json
Since #2392 the config schema is not in the same place anymore. Downstream fix: https://github.com/ory/ci/pull/50
> fix: version schema

- docs/docs/sdk.md
- docs/versioned_docs/version-v1.10/sdk.md
Adds a link to the .NET sdk.
the changes.
works.
> docs: add dotnet sdk

- docs/docs/sdk.md
- docs/versioned_docs/version-v1.10/sdk.md
> chore: fix sdk links

- .docker/Dockerfile-alpine
- .docker/Dockerfile-build
- .docker/Dockerfile-scratch
- .docker/Dockerfile-sqlite
- docs/docs/sdk.md
- go.mod
- go.sum
Update base images to remove potential sec vulns 
the changes.
works.
> chore: Bump base alpine images

- docs/docs/sdk.md
- docs/versioned_docs/version-v1.10/sdk.md
closes https://github.com/ory/hydra/pull/2458/files
the changes.
works.
> docs: add php link sdk page & fix links

- go.mod
- go.sum
- spec/api.json
> chore: update vulnerable jwt-go

- docs/sidebar.json
> feat: global docs sidebar and added cloud pages

- docs/docs/guides/consent.mdx
- docs/docs/guides/login.mdx
- docs/docs/guides/logout.mdx
- docs/versioned_docs/version-v1.10/guides/consent.mdx
- docs/versioned_docs/version-v1.10/guides/login.mdx
- docs/versioned_docs/version-v1.10/guides/logout.mdx
- docs/versioned_docs/version-v1.8/guides/consent.mdx
- docs/versioned_docs/version-v1.8/guides/login.mdx
- docs/versioned_docs/version-v1.8/guides/logout.mdx
- docs/versioned_docs/version-v1.9/guides/consent.mdx
- docs/versioned_docs/version-v1.9/guides/login.mdx
- docs/versioned_docs/version-v1.9/guides/logout.mdx
https://ory-community.slack.com/archives/C012RBW0F18/p1621977892051700
As discussed in slack @vinckr, a little clearer wording for the notice about HTML forms in the hydra docs.
the changes.
works.
I edited the notice in all doc versions, let me know if you want it done another way :)
> docs: Clearer wording in SPA notice for HTML forms

- .github/ISSUE_TEMPLATE/config.yml
- .github/pull_request_template.md
- CODE_OF_CONDUCT.md
- README.md
- internal/httpclient/models/volume.go
- spec/api.json
Updated repository templates to https://github.com/ory/meta/commit/ad9a6404080b7fb14d2d265ac0a2d4b685624d9b.
> chore: update repository template to ad9a6404

- README.md
Same as https://github.com/ory/kratos/pull/1439
> chore: coc shield

- README.md
https://github.com/ory/hydra/issues/2578
I didnt find the exemplary consent app in Go, (is it in https://github.com/ory/sdk/tree/master/clients/hydra/go ?)
the changes.
works.
> fix: README exemplary apps

- README.md
- internal/httpclient/models/plugin_config_interface.go
- internal/httpclient/models/volume.go
- spec/api.json
Updated repository templates to https://github.com/ory/meta/commit/9eaaf9b10f7713120aea9fe435fb73d49be29acd.
> chore: update repository template to 9eaaf9b1

- docs/docs/index.md
- docs/versioned_docs/version-v1.10/index.md
Fixing some things in the Hydra Introduction.
the changes.
works.
> fix: intro docs

- .goreleaser.yml
Closes #2160
the changes.
works.
> fix: no more windows workaround

- cmd/serve.go
- docs/docs/cli/hydra-serve-admin.md
- docs/docs/cli/hydra-serve-all.md
- docs/docs/cli/hydra-serve-public.md
- docs/docs/cli/hydra-serve.md
Closes #2366
the changes.
works.
> docs: link to correct doc in help command

- .github/ISSUE_TEMPLATE/config.yml
- docs/docs/cli/hydra-janitor.md
Updated repository templates to https://github.com/ory/meta/commit/d066e55a5d42c40f34c31ef55d8eac1fdd3179c8.
> chore: update repository template to d066e55a

- docs/docs/debug.mdx
> docs: section for debugging jwks based client errors

- .circleci/config.yml
> ci: bump goreleaser

- docs/docs/guides/kubernetes-helm-chart.mdx
Updating this file so that changes gets propagated to next versions
This PR relates to pull #2724
> Updated installation section helm command

- docs/versioned_docs/version-v1.10/guides/kubernetes-helm-chart.mdx
Updated installation section where I missed to do it in my previous pull #2719
This change is related to pull #2719  where missed to update the installation section which is important and is in first part of the page.
> Correction made to installation section

- docs/versioned_docs/version-v1.10/.static/api.json
This commit renders the docs to be in parity with an earlier change [1]
Reference(s):
[1] https://github.com/ory/hydra/pull/2706
the changes.
works.
> fix: list oauth2 clients query parameter 'name' -> 'client_name'

- docs/docs/guides/oauth2-token-introspection.mdx
- docs/versioned_docs/version-v1.10/guides/oauth2-token-introspection.mdx
> Close 2751

- docs/docs/advanced.md
> fix: docs  broken note

- .docker/Dockerfile-alpine
- .docker/Dockerfile-build
- .docker/Dockerfile-scratch
- .docker/Dockerfile-sqlite
- .github/workflows/cve-scan.yaml
- Makefile
- Introduce a new check, which build local images and scans for CVE. Currently any high or critical issues will fail the pipeline and generate a report
- Update alpine version to fix CVE
the changes.
works.
> feat: introduce cve scanning

- cmd/keys_import.go
- docs/versioned_docs/version-v1.10/cli/hydra-clients-import.md
#2732 
Based on the comment from the issue opener I tried to make the documentation correct, if there is anything that needs changing I would be happy to make changes.
> fix: documentation correction mentioned in the issue (#2732)

- docs/docs/guides/oauth2-public-spa-mobile.mdx
Fixes #2585 
the changes.
works.
> chore: document consent requirement for non-https redirect schemes

- docs/docs/.static/api.json
- docs/docs/install.md
> fix: update v1.10 installation instructions for linux

- .circleci/config.yml
- Makefile
- docs/docs/.static/api.json
- docs/docs/contributing.md
> fix: bump deps

- CONTRIBUTING.md
- docs/docs/5min-tutorial.mdx
- docs/docs/benchmark.md
Miniscule improvements to the docs
* The 5 minute tutorial better reflects which database backends are available
* Contribution guidelines are somewhat easier to follow
(third time's the charm)
None, just something I stumbled upon.
the changes.
works.
> docs: add options for using SQLite & Cockroach DB to 5min tutorial

- .github/workflows/ci.yaml
- go.mod
- go.sum
Maintains consistency with other actions.
> chore: move checkout to ory/ci/changelog

- driver/config/provider.go
- driver/config/provider_test.go
- driver/factory.go
- driver/registry_base_test.go
- driver/registry_sql_test.go
- hsm/manager_hsm_test.go
- internal/driver.go
> fix: add context where needed

- go.mod
- go.sum
- persistence/sql/persister_oauth2.go
- x/fosite_storer.go
> fix: comply with new fosite persister interface

- .github/workflows/ci.yaml
Fixes the branch protection error.
> fix: pass token to render-version-schema

- .schema/openapi/patches/meta.yaml
Closes https://github.com/ory/sdk/issues/153
the changes.
works.
> fix(sdk): incorrect title

- driver/registry_base.go
Closes #3021
the changes.
works.
Previously the audit logger did not pick up the configuration.
> fix: configure audit logger

- persistence/sql/persister_oauth2.go
While resolving an issue in my own implementation of storage for Fosite which has been modeled after Hydra's, I realized:
* There is unnecessary transaction in this function. The first query (deleting expired assertions) is completely unrelated from the other one (inserting a new assertion). In fact, deletion could even be done as a background job and not inside this function (in fact, why it is not a background job, or in a goroutine).
* Transaction isolation level used here is a default one for the connection (i.e., read committed) while `BeginTX` uses `LevelRepeatableRead`. Is this on purpose or is this a bug? In my implementation I always used the same way to create a transaction so I always had repeatable read transactions, which combined with the unnecessary transaction in this …
> fix: Remove unnecessary transaction

- .github/workflows/ci.yaml
- spec/config.json
- test/e2e/circle-ci.bash
> fix: use default for env var

- consent/doc.go
Closes #3033
the changes.
works.
> fix: add limit and offset to pagination

- Makefile
- consent/handler_test.go
- consent/strategy_default_test.go
- consent/strategy_oauth_test.go
- flow/flow.go
- flow/flow_test.go
- package-lock.json
- x/contextx/root_context.go
- x/contextx/test_context.go
Closes #2914
Closes #3085
See #2824
the changes.
works.
> fix: allow retries of unused login & consent requests

- spec/config.json
> fix: fixed configuration editor for the documentation page

- internal/httpclient-next/api/openapi.yaml
- internal/httpclient-next/api_admin.go
- internal/httpclient-next/api_public.go
- internal/httpclient-next/docs/PublicApi.md
- internal/httpclient-next/docs/WellKnown.md
- internal/httpclient-next/model_well_known.go
- internal/httpclient/client/admin/admin_client.go
- internal/httpclient/client/admin/delete_o_auth2_token_responses.go
- internal/httpclient/client/admin/flush_inactive_o_auth2_tokens_responses.go
- internal/httpclient/client/admin/introspect_o_auth2_token_responses.go
- internal/httpclient/client/public/discover_open_id_configuration_responses.go
- internal/httpclient/client/public/oauth2_token_responses.go
- internal/httpclient/client/public/oauth_auth_responses.go
- internal/httpclient/client/public/public_client.go
- internal/httpclient/client/public/revoke_o_auth2_token_responses.go
- internal/httpclient/client/public/userinfo_responses.go
- internal/httpclient/models/o_auth2_client.go
- internal/httpclient/models/well_known.go
- oauth2/handler.go
- spec/api.json
- spec/swagger.json
> fix(sdk): handle all error codes

- .github/workflows/ci.yaml
- Makefile
- quickstart-cockroach.yml
> chore: upgrade crdb to v22.x

- cmd/cli/handler_janitor.go
- cmd/cli/handler_migrate.go
- cmd/serve.go
- cmd/serve_admin.go
- cmd/serve_all.go
- cmd/serve_public.go
- cmd/server/handler.go
- driver/config/helper.go
- driver/config/provider.go
- driver/config/provider_test.go
- driver/config/tls.go
- driver/factory.go
- internal/certification/scripts/start.sh
- internal/config/config.yaml
- quickstart.yml
- scripts/run-bench.sh
- spec/config.json
- test/e2e/circle-ci.bash
- test/e2e/docker-compose.yml
- x/redirect_uri.go
- x/redirect_uri_test.go
> Refactor security setup

- cmd/server/handler.go
- consent/strategy_default.go
- consent/strategy_default_test.go
- driver/config/provider.go
- internal/driver.go
> Fix cookie setup

- contrib/quickstart/gitlab/config/gitlab.rb
- driver/config/serve.go
- internal/.hydra.yaml
- internal/certification/scripts/install.sh
- internal/config/config.yaml
- spec/config.json
BREAKING CHANGE: Configuration keys have changed:
```patch
serve: {
public: {
-    access_log: {
+    request_log: {
disable_for_health: true
},
},
admin: {
-    access_log: {
+    request_log: {
disable_for_health: true
},
}
}
```
> refactor: rename `access_log` to `request_log`

- spec/config.json
> fix: remove deprecated config value

- consent/strategy_default_test.go
- spec/config.json
> chore: clean up and reorg

- cmd/cmd_delete.go
- cmd/cmd_get.go
- cmd/cmd_import.go
- cmd/cmd_list.go
- cmd/cmd_perform.go
- cmd/cmd_update.go
- cmd/create.go
- cmd/output_client.go
- cmd/output_token.go
- oauth2/handler.go
- oauth2/oauth2_client_credentials_test.go
> fix(oauth2): incorrect TTL override

- .editorconfig
- .schema/version.schema.json
https://github.com/ory/hydra/runs/7611853855?check_suite_focus=true#step:2:934
> chore: update version schema to be compatible with current ory/cli

- client/client.go
> fix: omit null lifespans

- .github/workflows/ci.yaml
- client/sdk_test.go
- cmd/cmd_helper_test.go
- cmd/cmd_import_client_test.go
- driver/config/provider_test.go
- driver/registry_base.go
- driver/registry_base_test.go
- internal/httpclient/api_admin.go
- internal/httpclient/api_metadata.go
- internal/httpclient/api_v0alpha2.go
- internal/httpclient/client.go
- oauth2/handler_fallback_endpoints_test.go
- oauth2/handler_test.go
- oauth2/oauth2_auth_code_test.go
- test/conformance/run_test.go
- test/mock-client/main.go
> chore: change metric name

- .schema/version.schema.json
https://github.com/ory/hydra/runs/8022044955?check_suite_focus=true
> docs: add required key to all versions in the version schema

- README.md
Tests are not running on CircleCI anymore.
the changes.
works.
> docs: remove mention of CircleCI

- .docker/Dockerfile-hsm
Fixes quickstart-hsm docker image building
the changes.
works.
> fix: quickstart-hsm docker image build

- cmd/janitor.go
This PR fixes the hydra janitor command description that break the Docusaurus build of the docs portal: 
https://github.com/ory/docs/runs/8223524270?check_suite_focus=true
the changes.
works.
> chore: fix CLI command description

- cmd/cli/handler.go
- cmd/cliclient/client.go
- cmd/cmd_create_client.go
- cmd/cmd_create_jwks.go
- cmd/cmd_delete_client.go
- cmd/cmd_delete_jwks.go
- cmd/cmd_delete_tokens.go
- cmd/cmd_get_client.go
- cmd/cmd_get_jwks.go
- cmd/cmd_helper_client.go
- cmd/cmd_import_client.go
- cmd/cmd_import_jwk.go
- cmd/cmd_introspect_token.go
- cmd/cmd_list_clients.go
- cmd/cmd_perform_authorization_code.go
- cmd/cmd_perform_client_credentials.go
- cmd/cmd_revoke_token.go
- cmd/cmd_update_client.go
- quickstart.yml
> feat: improve cloud cli compatibility

- driver/config/provider.go
- driver/registry_sql_test.go
- persistence/sql/persister_client.go
> test: fix failing master pipeline

- .docker/Dockerfile-sqlite
> feat: add SQLite dependency to SQLite Dockerfile

- persistence/sql/persister_oauth2.go
Optimise SQL update to avoid redundant writes, which may lead to a high number of iops on postgresql engines.
This change will not change the behaviour of the code. It is only an optimisation of the update, so Postgresql does not need to spend unneccessary resources on vaccuming. I assume that the actual update is going to perform slightly better as well.
fixes #3137 
the changes.
works.
> fix: reduce number of iops on postgresql engines

- cmd/output_introspection.go
> fix: proper introspection output format

- Makefile
- cmd/root.go
- quickstart.yml
> fix: get started guides and missing CLI command

- cmd/cmd_import_jwk.go
Closes #3343
the changes.
works.
> fix: incorrect jwk import order

- cmd/cmd_introspect_token.go
Updated the CLI help text to show a correct example of `ory introspect token`.
the changes.
works.
> chore: fix introspect command CLI example

- .docker/Dockerfile-alpine
- consent/strategy_default.go
- consent/strategy_default_test.go
- driver/config/provider.go
- driver/config/provider_fosite.go
- driver/config/provider_test.go
- driver/registry_base.go
- driver/registry_base_test.go
- go.mod
- go.sum
- jwk/aead.go
- x/registry.go
> fix: no longer auto-generate system secret

- test/conformance/Dockerfile
> fix: broken OIDC images

- persistence/sql/persister_oauth2.go
Fixes #3485
the changes.
works.
> fix: double hashing of access token signature

- cmd/server/handler.go
> fix: sqa config values unified across projects

- go.mod
- go.sum
- oauth2/handler.go
> chore: remove unneeded dependency

- test/e2e/oauth2-client/package-lock.json
- test/e2e/oauth2-client/package.json
> fix: update nodemon version for oauth2 client

- .docker/Dockerfile-alpine
- .docker/Dockerfile-build
- .docker/Dockerfile-hsm
- .docker/Dockerfile-scratch
- .docker/Dockerfile-sqlite
- .github/workflows/cve-scan.yaml
- Makefile
the changes.
works.
- Bump alpine to 3.18
- Update dependencies for CVE scanners
- Scan real artifact
> chore: update security scanners

- persistence/sql/migrations/20211004110003000000_change_client_primary_key.cockroach.up.sql
Referring to issue https://github.com/ory/hydra/issues/3535 this PR is intended to fix the Cockroach migration bug when upgrading Hydra from v1.11.10 to v2.
the changes.
works.
> fix: cockroach migration error when hydra upgrades v2

- persistence/sql/migrations/20211004110003000000_change_client_primary_key.cockroach.up.sql
> Revert "fix: cockroach migration error when hydra upgrades v2"

- cmd/cmd_perform_authorization_code.go
> feat(cmd): add route that redirects to the auth code url

- cmd/server/handler.go
> fix: use correct tracer in middleware

- .github/CODEOWNERS
> chore: add hperl as codeowner

- .docker/Dockerfile-build
> fix: docker build

- oauth2/handler.go
Closes https://github.com/ory/client-go/issues/2
the changes.
works.
> fix: correct id token type in token exchange response

- .docker/Dockerfile-build
- .docker/Dockerfile-distroless-static
- .docker/Dockerfile-hsm
according to https://github.com/GoogleContainerTools/distroless/issues/1342
> chore: bump docker base images

- go.mod
- go.sum
> chore: upgrade ory/x

- .github/CODEOWNERS
- driver/factory.go
Adds yours truly as code owner.
> feat: add Inspect hook to registry constructor

- oauth2/handler.go
> fix: wrap authorize response in transaction

- .docker/Dockerfile-alpine
- .docker/Dockerfile-scratch
- .docker/Dockerfile-sqlite
- .github/workflows/cve-scan.yaml
> chore: add kubescape image scanner

- jwk/handler.go
- jwk/manager_strategy.go
> docs: document custom JWKs in broadcast endpoint

- cmd/cmd_create_client.go
- contrib/quickstart/gitlab/config/gitlab.rb
- test/conformance/run_test.go
fix some comments
the changes.
works.
> chore: fix some comments

- cmd/server/banner.go
> chore: update newsletter link

- jwk/manager_strategy.go
- persistence/sql/persister_jwk.go
- x/hasher.go
> fix: correct span names

- consent/handler.go
See https://github.com/orgs/ory/discussions/118
> revert: change comment on revokeOAuth2LoginSessions (#3853)

- oauth2/.snapshots/TestHandlerWellKnown-hsm_enabled=false.json
- oauth2/.snapshots/TestHandlerWellKnown-hsm_enabled=true.json
Patches oauth2 snapshots to reflect recent changes in `oauth2/handler.go` [`ResponseModesSupported`](https://github.com/ory/hydra/commit/9cc5f28825bb80398a9830d4fcb220147f74504c#diff-dc5158991c1ce571f0a59c32b86d6fc64c55fbe11d67cdee44b1b0ae436569df)
patches tests from #3861
the changes.
works.
> test: patch oauth2 snapshots

- .golangci.yml
- cmd/.snapshots/TestUpdateClient-case=updates_from_file-file=from_disk.json
- cmd/.snapshots/TestUpdateClient-case=updates_from_file-file=stdin.json
- cmd/cmd_create_client.go
- cmd/cmd_helper_client.go
- cmd/cmd_import_client_test.go
- cmd/cmd_update_client.go
- cmd/cmd_update_client_test.go
Simple CLI feature to support updating a client from files. Useful for external versioning.
> feat: update clients from files through the CLI

- .schema/config.schema.json
The side https://www.ory.sh/docs/hydra/reference/configuration-editor is broken - see chrome F12 console.
Broken githubusercontent link. The link was generated by a bot, so I guess this PR is invalid?
Consider using https://raw.githubusercontent.com/ory/x/master/otelx/config.schema.json instead - currently they are identical.
the changes.
works.
> fix: update config.schema.json link

- go.mod
- go.sum
To fix a regression in the migrator on CRDB.
> chore: bump ory/x

- persistence/sql/migrations/20241012144910000001_unused_indices.down.sql
- introduced in https://github.com/ory/hydra/pull/3859/files#diff-df8632a202f9781bec865fb0ca681eaa3b36a73384677e1729ab729eb3e1a532R13
the changes.
works.
> fix: rename index in down migration

- consent/handler.go
> docs: update clarification

- consent/handler.go
- oauth2/handler.go
> chore: improve oauth2 event data
