ory/hydra

.travis.yml

Fix error where vet cmd package cannot be found.
The package seems to be included in go now. No need to download it
anymore.

Remove go get of govet in .travis.yml

---

README.md

Fixed the spelling mistake. It should be "whether" instead of "weather".

Fix typo of weather

---

cmd/cli/handler.go
cmd/cli/handler_warden.go
cmd/server/handler_oauth2_factory.go
cmd/token_validate.go
oauth2/consent_strategy.go
oauth2/consent_test.go
oauth2/oauth2_test.go
sdk/client_opts.go
sdk/client_opts_test.go

This PR introduces `hydra token validate <token> --scopes=[a,b]`

cli: add token validation

---

warden/handler.go
warden/warden_test.go

`firewal.Context.Audience` overridden with requesting clients subject in `TokenAllowed` and `TokenValid`
Fix #237

warden: firewal.Audience overridden with requesting clients subject

---

docs/faq/operations.md

Resolves #197 
Signed-off-by: Matt Vinall <boyvinall@gmail.com>

docs: add notes on operational considerations

---

.travis.yml

Issue #285 
Not sure if this fix will work or not, as I could not get it building on my forked repo in travis-ci.
Anyways, something like this should do the trick

travis: Only gox build on tags and go1.7

---

client/manager_sql.go
client/manager_test.go

Found the bug when I couldn't set/update the client name of a client.
Signed-off-by: John Wu <johnwu96822@gmail.com>

Fix client SQL manager missing client_name

---

cmd/cli/handler.go
cmd/cli/handler_recovation.go
cmd/root_test.go
cmd/server/handler_oauth2_factory.go
cmd/token_revoke.go
cmd/token_validate.go
docs/sdk/go.md
firewall/warden.go
oauth2/fosite_store_sql.go
oauth2/handler_consent_test.go
oauth2/revocator_http.go
oauth2/revocator_test.go
oauth2/session.go

An issue with token revocation has been resolved, and I added an hydra token revoke CLI command:
```
$ hydra token client
XxDIiLvQnnB_4LUyMcrgDBMxz-EV4kVWd_HdK7bg0Nw.rQDfXz3-Uc3lPxgB2U-PwsgPhw2P-JwgHaydiPh0cfE
$ hydra token revoke XxDIiLvQnnB_4LUyMcrgDBMxz-EV4kVWd_HdK7bg0Nw.rQDfXz3-Uc3lPxgB2U-PwsgPhw2P-JwgHaydiPh0cfE
Revoked token XxDIiLvQnnB_4LUyMcrgDBMxz-EV4kVWd_HdK7bg0Nw.rQDfXz3-Uc3lPxgB2U-PwsgPhw2P-JwgHaydiPh0cfE
$ hydra token validate XxDIiLvQnnB_4LUyMcrgDBMxz-EV4kVWd_HdK7bg0Nw.rQDfXz3-Uc3lPxgB2U-PwsgPhw2P-JwgHaydiPh0cfE
Could not validate token: Token is malformed, expired or otherwise invalid
```

oauth2/revocation: token revocation fails silently with sql store

---

README.md
docs/install.md

> Usage:	docker run [OPTIONS] IMAGE [COMMAND] [ARG...]
Without this commit, the container name is not 'my-hydra'. As `--name` is an option it should be before the image's name.

docker: --name should be before the image's name

---

docs/oauth2.md

I guess the missing word is "use".
Signed-off-by: Bruno Bigras <bigras.bruno@gmail.com>

add missing work in docs/oauth2.md

---

cmd/server/helper_cert.go

HTTPS_TLS_CERT and HTTPS_TLS_KEY environment variables can contain `\n`
see:https://github.com/ory-am/hydra/blob/master/cmd/host.go
This commit replaces the `\n` characters with an actual newline to allow
the tls package to correctly create a X509 key pair.
Otherwise the X509 key pair fails to get created.
Signed-off-by: Edward Wilde <ewilde@gmail.com>

cmd: replace newline in HTTP_TLS

---

docs/oauth2.md

There wasn't any information about the auth code exchange, nor the required headers for that call. I've added this to the flow steps already present.
Not sure if this is the appropriate location for it, lemme know if I need to move this to another document.
context: https://github.com/ory/hydra/issues/385#issuecomment-284904456

Added information about auth code exchange to oauth2 docs

---

glide.lock

The new custom policy `StringPairsEqualCondition ` in Ladon is included with the latest commit to the project. Now updating Hydra's `glide.lock` file to respect this newest commit in Ladon.

Updated ladon version in glide.lock

---

cmd/clients_create.go

spf13's pflag just uses plain csvs without brackets

Dropping brackets in Create Client example

---

client/handler.go
cmd/server/handler.go
cmd/server/handler_health_factory.go
doc.go
doc_swagger.go
docs/api.swagger.yaml
health/handler.go
jwk/handler.go
oauth2/handler.go
policy/handler.go
warden/group/doc.go
warden/group/handler.go

docs: add health check to swagger and resolve swagger issues

---

cmd/server/handler.go

cmd/server: print full error message on http startup

---

cmd/host.go
cmd/root.go
cmd/server/handler.go
oauth2/handler.go
oauth2/handler_test.go
oauth2/oauth2_test.go

In order to support running Hydra with a different path prefix behind
a proxy, issue a challenge token with an issuer-prefixed auth redirect
URL instead of the URL received with the auth request.
Based on discussion in #352

oauth2: use issuer-prefixed auth URL in challenge redirect

---

docs/install.md

"Build from source" section in https://ory.gitbooks.io/hydra/content/install.html#installing-hydra is different than https://github.com/ory/hydra/blob/master/README.md

[DOC] Update "Build from source" section to actual state

---

config/config.go
config/config_test.go
health/doc.go
health/handler.go

Removes TLS restriction on health endpoint when termination is set - closes #586

health: disable TLS restriction for health check

---

.travis.yml
scripts/run-deploy.sh

This is required because before_deploy is ran twice if multiple providers exist, see https://github.com/travis-ci/travis-ci/issues/2570

travis: move deploy scripts to its own file

---

.travis.yml
Gopkg.toml
cmd/server/helper_cert.go
glide.lock
glide.yaml
jwk/cast.go
jwk/generator.go
jwk/generator_ecdsa256.go
jwk/generator_ecdsa521.go
jwk/generator_hs256.go
jwk/generator_rs256.go
jwk/generator_test.go
jwk/handler.go
jwk/handler_test.go
jwk/helper.go
jwk/manager.go
jwk/manager_http.go
jwk/manager_memory.go
jwk/manager_sql.go
jwk/manager_test_helpers.go
sdk/consent_test.go

This is a patch against v0.9.13, and requires #605, but there was no branch based on that at present, so I apologize for requesting this against master.
This adds a Gopkg.toml file so that [dep](https://github.com/golang/dep) can be supported. You can continue to use glide if you keep the Gopkg.toml up-to-date too. The reason that this is useful, for packages that use the hydra sdk, is that dep will recursively resolve dependencies using the Gopkg.toml file.
Right now, we have to add overrides for each of hydra's dependencies which is less than ideal.

Support dep

---

docs/install.md

bash command that contain regex needs to be quoated, version doesn't exists
Before creating your pull request, make sure that you have
[signed the DOC](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md#developers-certificate-of-origin). You can ammend your
signature to the current commit using `git commit --amend -s`.
Please create PRs only for bugs, or features that have been discussed with the maintainers, either at the
[ORY Community](https://community.ory.am/) or join the [ORY Chat](https://gitter.im/ory-am/hydra).

docs: fix bash command and version used in tutorial

---

docs/oauth2.md

updated some language words and corrected spelling

docs: fixed spelling and wording

---

docs/install.md
docs/oauth2.md

this PR updated the installation docs to reflect the latest hydra version at the time and the consent app.
also it fixes a mistake in assigning the consent scope.
I have ran through the installation with this update and was able to reach the end without any issues.

docs: updated hydra version in the tutorial to v0.10.0-alpha.8 and consent app to v0.10.0-alpha.9

---

docs/api.swagger.yaml
warden/group/doc.go
warden/group/handler.go
warden/group/manager.go
warden/group/manager_http.go
warden/group/manager_memory.go
warden/group/manager_sql.go
warden/group/manager_test.go
warden/group/manager_test_helper.go

This is to satisfy #594 
I'm not sure if the `api.swagger.yaml` file is complete/correct since the `gen-swagger.sh` script produces the uncommitted `api.swagger.json` file.
The API is also a little strange as the `GET /warden/groups` endpoint already existed and previously required a `member` param (and `GET /warden/groups/<id>` refers to the group id, not the member id).
Now `GET /warden/groups` _OPTIONALLY_ uses the `member` param. If it exists, the behavior is the same as before so there are no API regressions.
However, if `member` does not exist, then it is assumed that the user wants to list all groups. In this case, the required policy resource changes (from `rn:hydra:warden:groups:<member>` to `rn:hydra:warden:groups`). Additionally, the `limit` and `offset` parameters are used if …

add ability to list all groups

---

cmd/keys_create.go
docs/api.swagger.yaml
jwk/handler.go
jwk/handler_test.go
jwk/manager_test.go
jwk/manager_test_helpers.go

I think this is all that's necessary to support #627 
It looks like support for ES256 is available (`jwk/generator_ecdsa256.go`), but that the JWK handler doesn't support it (https://github.com/ory/hydra/blob/master/jwk/handler.go#L27-L38).
Go's P-256 is implementation is constant-time (which prevents certain types of attacks) while its P-384 and P-521 are not (https://github.com/gtank/cryptopasta).

Support ES256 JWK Algo

---

cmd/cli/handler_policy.go

Removed the line that added a subject back after it removed it.
I also added a couple of `\n` on fmt.Printfs that didn't have them.

cli: Fix hydra cli adding policy subjects on subject remove

---

.circleci/config.yml
CHANGELOG.md
ISSUE_TEMPLATE.md
PULL_REQUEST_TEMPLATE.md
README.md
UPGRADE.md

Add changelog

---

Gopkg.lock
Gopkg.toml
oauth2/revocator_test.go

Currently, it is possible to revoke tokens using any client. This PR requires the client making the revokation request to be the same as the one from the OAuth2 request.
> The authorization server first validates the client credentials (in
case of a confidential client) and then verifies whether the token
was issued to the client making the revocation request. If this
validation fails, the request is refused and the client is informed
of the error by the authorization server as described below.
Upstream http://github.com/ory/fosite/issues/225

oauth2: Fixes clients being able to revoke any token

---

Gopkg.lock
Gopkg.toml
cmd/server/handler_oauth2_factory.go
compose/firewall.go
docs/api.swagger.json
oauth2/handler.go
oauth2/handler_struct.go
oauth2/introspector_test.go
sdk/go/hydra/swagger/consent_request.go
sdk/go/hydra/swagger/context.go
sdk/go/hydra/swagger/docs/ConsentRequest.md
sdk/go/hydra/swagger/docs/Context.md
sdk/go/hydra/swagger/docs/Handler.md
sdk/go/hydra/swagger/docs/OAuth2Api.md
sdk/go/hydra/swagger/handler.go
sdk/go/hydra/swagger/o_auth2_api.go
sdk/js/swagger/docs/ConsentRequest.md
sdk/js/swagger/docs/Context.md
sdk/js/swagger/docs/Handler.md
sdk/js/swagger/docs/OAuth2Api.md
sdk/js/swagger/src/api/OAuth2Api.js
sdk/js/swagger/src/model/ConsentRequest.js
sdk/js/swagger/src/model/Context.js
sdk/js/swagger/src/model/Handler.js

From now on, requests introspecting tokens require the client making the request (as identified by the Authorization header) to be allowed to access that endpoint. If an OAuth 2.0 token is given, the scope `hydra.introspect` is required additonally to a policy granting access to `rn:hydra:oauth2:tokens` with action `introspect`.

oauth2: Requires firewall check for introspecting access tokens

---

.circleci/config.yml
Dockerfile-alpine
UPGRADE.md

Reintroduces alpine based docker image

---

cmd/cli/handler_policy.go
cmd/policies_import.go

cmd: Adds a dedicated command for importing policies

---

composer.json

Composer complained because an unknown license was used "Apache 2.0" instead of "Apache License 2.0". This patch resolves that.

sdk: Resolves composer license complaint

---

client/handler.go
client/sdk_test.go
cmd/cli/handler_client.go

Previously a newly created public client had a secret send with the initial response and this secret was displayed in the CLI.
Now it is clear that there is no secret needed for public clients. It is not displayed in the CLI anymore.
closes #737

client: do not show/send secret when client is public

---

docs/security.md

The policy linked to as an example has since been removed. Just point to
a different policy instead.

docs: Fix dead link to example policy

---

oauth2/consent_strategy.go
oauth2/consent_strategy_test.go

This patch resolves a vulnerability in the consent flow. This vulnerability
affects versions 0.10.0 ~ 0.11.5 only. Versions < 0.10.0 are not affected.
The vulnerability can be exploited as follows:
1. Malice initiates an OAuth 2.0 Authorization Code Flow:
https://hydra/oauth2/auth?client=...
2. Hydra redirects malice to the consent app and appends consent
id "example-id": https://consent-app/?consent=example-id
3. Malice convinces Bob to open url https://consent-app/?consent=example-id
and authorize the access request.
4. The consent app would redirect Bob back to
`https://hydra/oauth2/auth?client=...&consent=example-id`. However,
through some means, Malice is able to prevent redirection of Bob's
user agent.
5. Malice accesses the original auth code url and appends the consent id: …

oauth2: Resolves possible session fixation attack

---

client/doc.go
client/handler.go
client/manager.go
client/manager_memory.go
client/manager_sql.go
client/manager_test.go
client/manager_test_helpers.go
client/sdk_test.go
cmd/server/handler_client_factory.go
cmd/server/helper_client.go
docs/api.swagger.json
oauth2/fosite_store_test.go
oauth2/oauth2_test.go
sdk/go/hydra/sdk_api.go
sdk/go/hydra/swagger/docs/OAuth2Api.md
sdk/go/hydra/swagger/o_auth2_api.go
sdk/js/swagger/docs/OAuth2Api.md
sdk/js/swagger/src/api/OAuth2Api.js
sdk/php/swagger/docs/Api/OAuth2Api.md
sdk/php/swagger/lib/Api/OAuth2Api.php

Previously, all clients were returned by `GET /clients`. To mitigate
DoS attacks against large databases, pagination has been introduced.
Closes #739

client: Introduces pagination to client management

---

oauth2/consent_strategy.go

This resolves an issue when different timezones are used between systems
by enforcing UTC everywhere.
Closes #679

oauth2: Forces UTC in consent strategy

---

cmd/connect.go

Before newsletter text did not seem to make clear that it is just for security information.
The text is updated according to #779, closes #779

Update newsletter text

---

.circleci/config.yml

Before forked PRs failed on circleci because $COVERALLS_REPO_TOKEN was not set. This token does seem not to be necessary at all because hydra is a public repository (see #782).
closes #782

Remove coveralls token from circleci config

---

cmd/root.go

Previously, the build time was always the current time. This patch
resolves that issue.
Closes #792

cmd: Resolves an issue with broken build time display

---

Gopkg.lock
Gopkg.toml
README.md
UPGRADE.md
docker-compose.yml
oauth2/fosite_store_sql.go
oauth2/fosite_store_test.go
oauth2/fosite_store_test_helpers.go
pkg/joinURL.go

This release resolves a security issue (reported by [platform.sh](https://www.platform.sh)) related to the fosite storage implementation in this project. Fosite used to pass all of the request body from both authorize and token endpoints to the storage adapters. As some of these values are needed in consecutive requests, the storage adapter of this project chose to drop all of the key/value pairs to the database in plaintext.
This implied that confidential parameters, such as the `client_secret` which can be passed in the request body since fosite version 0.15.0, were stored as key/value pairs in plaintext in the database. While most client secrets are generated programmatically (as opposed to set by the user) and most popular OAuth2 providers choose to store the secret in plaintext for …

oauth2: Resolves client secrets from potentially leaking to the database in cleartext

---

Gopkg.lock
Gopkg.toml
oauth2/handler.go
oauth2/introspector.go

This patch adds the ability to return the token type ("refresh_token", "access_token") upon token introspection.
Closes #831

oauth2: Returns token type on introspection

---

Gopkg.lock
Gopkg.toml
cmd/server/handler.go
cmd/server/handler_health_factory.go
config/config.go
health/handler.go
metrics/prometheus/metrics.go
metrics/prometheus/middleware.go
metrics/telemetry/metrics.go
metrics/telemetry/middleware.go
metrics/telemetry/middleware_test.go

Signed-off-by: Dmitry Dolbik <dolbik@gmail.com>
It is draft implementation to support Prometheus in Hydra (https://github.com/ory/hydra/issues/669). Prometheus collects all metrics and more then current telemetry does. Current telemetry and prometheus works together in this pull request
Added two new Prometheus metrics:
- Secure token service requests served per endpoint
- Secure token service response time per endpoint
The result of prometheus:
`
go_gc_duration_seconds{quantile="0"} 0
go_gc_duration_seconds{quantile="0.25"} 0
go_gc_duration_seconds{quantile="0.5"} 0
go_gc_duration_seconds{quantile="0.75"} 0
go_gc_duration_seconds{quantile="1"} 0
go_gc_duration_seconds_sum 0
go_gc_duration_seconds_count 0
go_goroutines 16
go_memstats_alloc_bytes 3.479416e+06
go_memstats_alloc_bytes_total …

[Prometheus] Add new prometheus metrics and metrics endpoint

---

cmd/cli/handler_migrate.go
cmd/migrate_sql.go
docker-compose.yml

cmd: Allows reading database from env in migrate sql

---

.gitignore
consent/strategy_default.go
consent/strategy_default_test.go

This patch resolves an issue where oidc_context would be included in the login request but not the consent request.
Closes #900

 consent: Propagates oidc_context to consent request

---

README.md

The old one 404's
Signed-off-by: Brandon Philips <bphilips@redhat.com>

README: fix docker linux link

---

Gopkg.lock
Gopkg.toml
client/handler.go
client/manager_memory.go
client/sdk_test.go
client/validator.go

client: Improve handling of legacy `id` field

---

cmd/cli/handler_helper.go

Asking for a non-existent client results in the following confusing error message:
```
Command failed because calling "GET http://hydra:4444/clients/no-such-client" resulted in status code "200" but code "404" was expected.
{"error":"Unable to locate the resource","error_description":"","status_code":404}
```
This commit fixes the expectedStatusCode and response.StatusCode arguments to fmt.Fprintf which were reversed.

cli: fix reporting of epected vs. received status codes

---

config/backend_plugin.go
config/backend_plugin_noplugin.go

Debugging Hydra in Go 1.10 and 1.11 (confirmed by one of its members),
is not possible due to [this unresolved
bug](https://github.com/golang/go/issues/23733) which is related to the
use of the plugin functionality.
This change allows passing a build tag which will disable plugin
implementation and therefore allow to debug in all the use-cases where
plugin backend is not needed.
Signed-off-by: Gorka Lerchundi Osa <glertxundi@gmail.com>

config: disable plugin backend through 'noplugin' tag 

---

consent/strategy_default.go
consent/strategy_default_test.go
consent/types.go

This resolves a panic when the session is not available. Closes #988

consent: Populate consent session with default values

---

UPGRADE.md
cmd/serve.go
cmd/server/handler.go

This patch introduces environment variable `CORS_ENABLED` which toggles CORS.
Closes #996

cmd: Disable CORS by default

---

Gopkg.lock
Gopkg.toml

Version 0.0.6 of sqlcon adds proper conflict detection to MySQL. Closes #1007

vendor: Upgrade sqlcon to 0.0.6

---

Gopkg.lock
client/client.go
client/manager_0_sql_migrations_test.go
client/manager_sql.go
client/manager_test_helpers.go
client/validator.go
cmd/server/handler.go
cmd/server/handler_oauth2_factory.go
cmd/server/helper_cors.go
cmd/server/helper_cors_test.go
oauth2/handler.go
oauth2/handler_fallback_endpoints_test.go
oauth2/handler_test.go
oauth2/introspector_test.go
oauth2/oauth2_auth_code_test.go
oauth2/oauth2_client_credentials_test.go
oauth2/revocator_test.go

Field `allowed_cors_origins` was added to OAuth 2.0 Clients. It enables
CORS for the whitelisted URLS for paths which clients interact with,
such as /oauth2/token.
Closes #975
Depends on:

oauth2: Enable client specific CORS settings

---

config/config.go

The MustValidate() function is sometimes called before any other logging
function has been called and this results in a crash. An easy way to
reproduce the crash is to change OAUTH2_ACCESS_TOKEN_STRATEGY=jwt in the
default docker-compose.yml
Signed-off-by: Vishesh Handa <vishesh.handa@telefonica.com>

config: Fix use of uninitialized logger

---

Gopkg.lock
Gopkg.toml
cmd/root.go
cmd/server/handler.go
config/config.go
config/config_test.go
docker-compose.yml
tracing/middleware.go
tracing/middleware_test.go
tracing/tracer.go

• Adds support for the [Jaeger Distributed Tracing System](https://www.jaegertracing.io/docs/)
• Docker setup for loading up Jaeger with Hydra
• The tracer can be configured w/ sampling via config https://www.jaegertracing.io/docs/sampling/
• By using the OpenTracing API, which is vendor neutral, will make adding support for other OpenTracing compliant tracers straightforward.
• This is the first step...the real work is to follow as we will need to span & propagate all teh things! (_e.g. db lookups, encryption, calls to the consent app, etc._)
I have updated the docker-compose to bring up the Jaeger tracer and added config for the Hydra container to use it as the collector.
• Clone Hydra to your GOPATH
• Checkout to this branch
• Run `docker-compose up --build`
_(Good time to grab a …

Add support for distributed tracing

---

cmd/server/helper_cert.go
config/config.go

Signed-off-by: Pierre-David Bélanger <pierredavidbelanger@gmail.com>
this PR fixes those two warnings:
github.com/ory/hydra/cmd/server
cmd/server/helper_cert.go:79: Logger.Warningf format %s has arg cert of wrong type crypto/tls.Certificate
github.com/ory/hydra/config
config/config.go:381: Logger.Fatalln call has possible formatting directive %d

two littles things that bugs me when I compile or run tests

---

Gopkg.lock
Gopkg.toml
consent/strategy_default.go
consent/strategy_default_test.go
jwk/jwt_strategy.go
jwk/jwt_strategy_test.go
oauth2/handler.go
oauth2/oauth2_auth_code_test.go

Bumps fosite version to 0.22.0: [changes between current (0.21.5 and 0.22.0)](https://github.com/ory/fosite/compare/v0.21.5...v0.22.0)
As seen in the diff, the breaking change was to the `JWTStrategy` interface as its methods now accept a context. Handlers have been updated as a result of this to pass along the request context down the call path.
_Review: @aeneasr_

Bump fosite version and integrate breaking changes

---

client/manager_test_helpers.go

Signed-off-by: Prateek Malhotra <someone1@gmail.com>

client: fix test to pass non-nil context

---

Gopkg.lock
Gopkg.toml
client/manager_memory.go
client/manager_sql.go
cmd/server/handler.go
cmd/server/handler_oauth2_factory.go
config/config.go
tracing/traced_bcrypt.go
tracing/traced_bcrypt_test.go

This PR beings to leverage our previous efforts on context propagation.
- Bumps fosite version to `0.23.0`: [changes between current (0.22.0) and 0.23.0](https://github.com/ory/fosite/compare/v0.22.0...v0.23.0)
As seen in the diff, the breaking change was to the Hasher interface as its methods now accept a context. Consumers have been updated to pass along the request context down the call path.
- Implements a instrumented bcrypt hasher which now creates spans on calls to `Hash` and `Compare`. Hydra will now use this `Hasher` implementation if tracing has been enabled. 
- 100% test coverage for new instrumented `Hasher`
- Each commit can be 🚢'ed independently in order
Here is a trace that is created by as a result of a successful call to `oauth2/token` endpoint for a client credentials …

Bump fosite version to 0.23.0 + New tracing instrumented Hasher

---

client/manager_sql.go
consent/manager_sql.go
integration/sql_schema_test.go
jwk/manager_sql.go
oauth2/fosite_store_sql.go

This PR continues on our efforts of context propagation by using the associated context aware methods in the sqlx package.
This is necessary for when we [wrap the db driver](https://github.com/golang/go/issues/18080#issuecomment-287867357) with the tracing API, we will start getting spans out of the box 😉.  
Furthermore, using these methods comes with the added benefit that database drivers that support context cancellation will be able to quit early if there is no hope of completing a query/tx.
_Review: @aeneasr_

tracing: use context aware database methods

---

oauth2/fosite_store_sql.go
oauth2/fosite_store_test.go
oauth2/fosite_store_test_helpers.go

Resolves #1067 by adding indices to:
• `request_id` column in the hydra_oauth2_access & hydra_oauth2_refresh tables
• `requested_at` column in the hydra_oauth2_access table
_Review: @aeneasr_

Add missing indices to resolve #1067

---

cmd/root_test.go

cmd: Fix flaky port finder

---

consent/manager_test_helpers.go
consent/sql_helper.go
consent/sql_helper_test.go

I believe this was missing from #1013. Responses from `GET /oauth2/auth/requests/consent/:challenge` have the `login_challenge` and `login_session_id` fields, but they're always empty strings, because they were not being converted from the database response.
This PR adds the missing fields to the relevant SQL converter test and implementation.
cc @aeneasr

Fix missing LoginChallenge and LoginSessionID from GetConsentRequest

---

jwk/handler.go
oauth2/handler.go

Based on the chat, we need to handle `OPTIONS request` with `corsMiddleware` too.
force push.

cors: add options cors middleware handler

---

cmd/cli/handler_migrate.go
cmd/server/handler_jwk_factory.go
config/backend_test.go
config/config.go
pkg/secret.go

This patch resolves an issue which made it impossible to rotate secrets because an un-hashed version was used.
Closes #1026

cmd: Resolve issues with secret migration

---

cmd/server/handler.go
cmd/server/handler_test.go

As discussed on discord.
Add the `/health/alive` route to the frontend httpRouter to be used for black box monitoring and/or health checks from external infrastructure (GCE loadbalancer for example).
force push.
Is there a place (in docs) where I need to define that `/health/alive` is now reachable via the frontend port? As far as I can see the API docs don't distinguish between frontend/backend routes.

health: Register healthx.AliveCheckPath route for frontend

---

cmd/token_user.go
go.mod
go.sum

cmd: Add https option to token user command

---

consent/manager_sql.go

Closes #1168
Signed-off-by: arekkas <aeneas@ory.am>

consent: Ignore row count in revoke

---

UPGRADE.md

none
Fix migrate sql command at upgrading guide.
`hydra migrate $DATABASE_URL` does not work.
But `hydra migrate sql $DATABASE_URL` works.
force push.
none

fix migrate sql command  at upgrading guide

---

UPGRADE.md

and better wording for api changes section

Remove duplicated refresh token section

---

client/handler.go
client/validator.go
cmd/cli/handler_jwk.go
cmd/server/handler_oauth2_factory.go
cmd/server/helper_keys.go
consent/manager.go
consent/manager_memory.go
consent/manager_sql.go
consent/strategy_default.go

I refactored the argument part of the function.

refactoring

---

client/client.go
oauth2/oauth2_auth_code_test.go

Signed-off-by: Steve Kaliski <sjkaliski@gmail.com>
https://github.com/ory/docs/issues/78, cc @aeneasr
The grant_type pattern is incorrect, replaces `authorize_code` with `authorization_code`.
force push.

client: rename grant type authorize_code to authorization_code

---

README.md

Migrate links from old docs to new docs

---

oauth2/fosite_store_helpers.go
oauth2/fosite_store_test.go
oauth2/oauth2_auth_code_test.go

Signed-off-by: Prateek Malhotra <someone1@gmail.com>
#1204
Exporting tests in the `oauth2` package again, removed  with https://github.com/ory/hydra/commit/3a10df9bff259dee9b0d635b6522e098fbdd8cc3#diff-88
force push.

[oauth2] export tests again

---

cmd/serve.go

The help message is missing separation of public and admin port.
force push.

Fix help output of hydra serve

---

cmd/serve.go
cmd/server/handler.go
config/config.go

This allows the use of strings like "unix:/path/to/socket" as PUBLIC_HOST and/or PRIVATE_HOST.
Signed-off-by: Janis Meybohm <meybohm@traum-ferienwohnungen.de>
In some environments (kubernetes for example) securing TCP ports is a little tricky. Supporting unix sockets makes it easy to "hide" the administrative API. 
force push.
I'm happy to add docs and tests (if applicable) if you're okay with this addition/change. …

Support binding frontend/backend to unix sockets

---

cmd/cli/handler_migrate.go

none
Show count of `NEW_SYSTEM_SECRET` length when `NEW_SYSTEM_SECRET` is too short
force push.
none

fix error message of too short NEW_SYSTEM_SECRET

---

cmd/token_flush.go

none
"1d" is unavailable unit so that I fixed token flush CLI description.
Only we can use  these units: "ns", "us" (or "µs"), "ms", "s", "m", "h".
https://godoc.org/time#ParseDuration
force push.

fix token flush CLI description

---

cmd/root.go
cmd/server/handler_oauth2_factory.go
config/config.go
config/config_test.go

none
Enable to validate by old system secret when setting `ROTATED_SYSTEM_SECRET`.
force push.
none

Enable to validate by old system secret

---

cmd/server/handler.go

`RejectInsecureRequests` handler fails for requests via socket because the remote address is `@`.
We should not reject insecure requests coming in via unix socket as there is no TLS support anyways.
```
{"error":"address @: missing port in address","level":"warning","msg":"Could not serve http connection","time":"2019-01-16T08:39:17Z"}
{"code":502,"details":{},"error":"Can not serve request over insecure http","level":"error","msg":"An error occurred while handling a request","reason":"","request-id":"","status":"","time":"2019-01-16T08:39:17Z", "trace":"
Stack trace: 
github.com/ory/hydra/cmd/server.(*Handler).RejectInsecureRequests
/go/src/github.com/ory/hydra/cmd/server/handler.go:303
github.com/ory/hydra/cmd/server.(*Handler).RejectInsecureRequests-fm …
```

Disable RejectInsecureRequest middleware on unix sockets

---

go.mod
go.sum

vendor: Bump ory/x to 0.0.35

---

.circleci/config.yml
Dockerfile
Dockerfile-alpine
go.mod
go.sum

Reluctantly this PR deals with 2 issues to pass CircleCI.
#1270
#1271 
force push.

docker: Bump base docker image versions

---

cmd/cli/handler_client.go
cmd/clients_create.go

This allows the creation of clients permitted to make CORS requests from
specific domains.
Signed-off-by: Josh Giles <jgiles@paxos.com>
This  follows up on #957, which added the server feature but not a way to specify the CORS origins in the cli.
Add a flag for setting the allowed CORS origins.
force push.

cmd: Add --allowed-cors-origins to client create.

---

cmd/clients_create.go

Fix description of `clients create --subject-type` option
(This was same as `--logo-uri`)
force push.

cmd: Fix description of clients create --subject-type option

---

cmd/token_user.go

Command `hydra token user --no-open` does not open up the browser since the `--no-open` flag check is inverted, similar to ory/hydra#1258 and https://github.com/ory/keto/pull/85
force push.

cmd: Fix no-open inverted flag check

---

cmd/cli/handler_client.go
cmd/cli/handler_helper.go
cmd/clients_list.go
go.mod
go.sum

#1310
Add `hydra clients list` command.
In this PR, command renders columns only `client_id`, `name`, `response type`, `scope`, `RedirectUris`, `GrantTypes`, `TokenEndpointAuthMethod`.
The command behaves like following.
```
$ go run main.go clients list --help
This command list an OAuth 2.0 Clients.
Example:
hydra clients list
Usage:
hydra clients list [flags]
Flags:
-h, --help        help for list
--limit int   The maximum amount of policies returned. (default 20)
--page int    The number of page. (default 1)
Global Flags:
--access-token string    Set an access token to be used in the Authorization header, defaults to environment variable OAUTH2_ACCESS_TOKEN
--endpoint string        Set the URL where ORY Hydra is hosted, defaults to environment variable HYDRA_ADMIN_URL …
```

cmd: Add clients list command

---

docker-compose.yml

replace unless-stopped values as they are not supported in used compose version (v2), for values supported in this compose version: on-failure. closes #1312.
CC\ @aeneasr

5min-tutorial: fix docker-compose wrong restart values

---

consent/manager_sql.go
consent/manager_test_helpers.go
consent/sql_helper.go

Signed-off-by: Kevin Minehart <kmineh0151@gmail.com>
#1256 
Previous PR: https://github.com/ory/hydra/pull/1301
If HandleConsentRequest is called a second time, then:
* If the request was not used (`was_used = false`), then the old ConsentRequest is replaced with the newly provided data.
* If the request was used (`was_used = true`), then the old ConsentRequest is returned, whereas previously a SQL error would be returned.
- [ x I confirm that this pull request does not address a security vulnerability. If this pull request addresses a security
by signing my commit(s). You can amend your signature to the most recent commit by using `git commit --amend …

Prevent errors when calling HandleConsentRequest a second time

---

package.json
package.oc.json
yarn.lock

This PR removes opencollective from the package.json, as it causes problems when npm installing this package.

Remove opencollective from package.json

---

docker-compose-mysql.yml
docker-compose-tracing.yml
docker-compose-twoc-mysql.yml
docker-compose-twoc.yml
docker-compose.yml
scripts/5min-tutorial.sh

#1321 #1196
* Update docker-compose to v3.
* Reorganize/refactor docker-compose config into multiple files for cleanness and readability.
I've detected six usecases of the docker-compose files.
1. postgres 
2. mysql
3. postgres + tracing
4. mysql + tracing
5. twoc-postgres
6. twoc-mysql
Instead of forcing the user to edit the `docker-compose.yml` and `docker-compose-twoc.yml` files by hand, the usage now would be:
1. docker-compose up --build
2. docker-compose -f docker-compose.yml -f docker-compose-mysql.yml up --build
3. docker-compose -f docker-compose.yml -f docker-compose-tracing.yml up --build
4. docker-compose -f docker-compose.yml -f docker-compose-mysql.yml -f docker-compose-tracing.yml up --build
5. docker-compose -f docker-compose-twoc.yml up --build
6. docker-compose -f …

docker: update docker-compose to v3 + docker-compose files refactor

---

cmd/root.go

Flag -c has accidentally been removed. This patch resolves that. Closes #1344

cmd: Reenable -c cli flag

---

cmd/cli/handler_migrate.go
cmd/serve.go
cmd/server/handler.go
driver/configuration/provider.go
driver/configuration/provider_viper.go
driver/configuration/provider_viper_test.go
driver/driver_default.go
driver/registry_base.go
go.mod
go.sum
internal/driver.go
x/redirect_uri.go
x/redirect_uri_test.go

This patch enables developers to whitelist insecure redirect URLs while using flag `--dangerous-force-http`.
Closes #1021

oauth2: Allow whitelisting insecure redirect URLs

---

client/handler.go
consent/handler.go
go.mod
go.sum

Signed-off-by: Kevin Minehart <kmineh0151@gmail.com>
#1361
This PR in ory/x: https://github.com/ory/x/pull/39
Instead of using `http.Header.Write(...)` in an attempt to write http headers, just use `http.ResponseWriter.Headers().Set(...)`.
force push.

Fix pagination headers

---

cmd/migrate_sql.go

Fixed help text to reference the correct environment variable which is now `DSN` instead of `DATABASE_URL`
force push.

cmd: fix help text on migrate cmd

---

cmd/server/handler.go
go.mod
go.sum

oauth2: Resolve memory leak in gorilla/sessions

---

oauth2/handler.go

Fixes some fallback routes to be named correctly and reference the correct config values.
force push.

fix fallback routes and templates

---

consent/strategy_default.go

#1409
"Remember" flag was reset to false after a 2nd login dance when the first login dance was "remembered.
I tried to follow instructions from @aeneasr on discord, but I am new to this project and oauth2...
force push.
I am still learning how the tests are structured, so I am still not sure how to add tests... I might need some guidance in order to add tests if you think tests need to be added.

Do not confirmLoginSession when skip is true to prevent remember reset to false

---

cmd/migrate_sql.go

https://github.com/ory/hydra/issues/1411
Simple changes the help message output when a user tries to invoke the `migrate sql` subcommand without specifying a database URL on the command line itself. Currently the message for `-e` indicates that it will pull from the `DSN` environment variable but not that it will check the `dsn` key in the indicated configuration file.
force push.

Fix migrate SQL command message regarding config file.

---

cmd/cli/handler_client.go
cmd/clients_create.go

cmd: allow to set the client's post-logout URIs

---

tracing/tracer.go

Support default Jaeger environment variables as described in https://github.com/jaegertracing/jaeger-client-go#environment-variables
Those variables can then be overridden by Hydra config/env as before.
Motivation:
This enables standard configuration of Jaeger helps in Kubernetes environment when those variables tend to be shared using configmap between different deployments.
Currently used environment variable `TRACING_PROVIDER_JAEGER_LOCAL_AGENT_ADDRESS` is not Kubernetes friendly - usually `JAEGER_AGENT_HOST` is populated instead with `status.hostIP`.

feat: support default jaeger environment variables

---

driver/configuration/provider_viper.go
go.sum

#1448 
Don't show `registration_endpoint` at `/.well-known/openid-configuration` if config is undefined.

 oauth2: Don't show registration_endpoint if config is undefined

---

UPGRADE.md
docs/config.yaml

The following link no longer exists
https://www.ory.sh/docs/hydra/advanced#system-secret-rotation
New link is here
https://www.ory.sh/docs/hydra/advanced#rotation-of-hmac-token-signing-and-database-and-cookie-encryption-keys

docs: Fix link to system secret rotation

---

cmd/server/handler.go
docs/config.yaml
driver/configuration/provider.go
driver/configuration/provider_viper.go
driver/configuration/provider_viper_test.go

#1278
This commit adds an option to disable access log for health endpoints.
This is especially helpful in environments like Kubernetes, where
special preprocessing filters would be required otherwise.

cmd: Add option to disable access log for health endpoints

---

README.md

Hello, ORY team!
We published project [Werther](https://github.com/i-core/werther) that is an Identity Provider for ORY Hydra. Werther authenticates users over LDAP.
We think it will be useful for the ORY Hydra community to have an Identity Provider that is ready to use. It would save the time needed to start working with the ORY Hydra.
If you are interested in it we will be glad to add the Werther link to the README page of the ORY Hydra.

docs: Add a link to Identity Provider "Werther" to community projects

---

docs/config.yaml
driver/configuration/provider_viper.go
tracing/tracer.go

This will provide compatibility with istio.
Fixes https://github.com/ory/hydra/issues/1447

tracing: Add support for B3 headers via the JAEGER_PROPAGATION env var

---

Makefile
go.mod
go.sum
jwk/manager_memory.go
jwk/manager_test_helpers.go

jwk: Fix memory mamager of JWK deletion

---

cmd/serve.go

cmd: Use commit hash instead of version for link to config

---

go.mod
go.sum

Using PKCE with private clients now returns an error message.
Closes #1512

vendor: Bump to fosite 0.29.7

---

consent/manager_memory.go
consent/manager_sql.go
consent/manager_test_helpers.go

I adjust `ListUserAuthenticatedClientsWithFrontChannelLogout` & `ListUserAuthenticatedClientsWithBackChannelLogout`, make it return unduplicated clients.
If one user login client A 100 times, and then logout after the latest login, it would send 100 requests to the front/backchannel of client A with the logout token with the same sid. It's a waste of performance to both Hydra and client A.

Consent: deduplicate user authenticated clients during logout.

---

driver/configuration/provider_viper.go
driver/configuration/provider_viper_test.go

https://github.com/ory/hydra/issues/1546
use TrimRight.

driver: Fix RP-Initiated Logout trailing slash bug

---

oauth2/doc.go
sdk/go/hydra/client/public/oauth2_token_parameters.go
sdk/go/hydra/models/swaggeroauth2_token_response.go

Add IdToken and Scope to oauth2_token_response.
These fields are presented in response and should be parsed.
Add RefreshToken field to oauth2_token_params.
With RefreshToken field we will be able to refresh Access token
by providing Refresh token.
Relates #1509
Relates #1533

SDK: enrich oauth2_token_response and params

---

Makefile
README.md

https://github.com/ory/hydra/issues/1507
- Create the task and correct readme.

develop: Makes init task in makefile and corrects readme

---

driver/registry.go

Removes an errant logging of the DSN. The DSN can include credentials which should not be logged.
related to https://github.com/ory/hydra/issues/1585 and https://github.com/ory/k8s/issues/55

driver: don't log DSN

---

doc.go

Correct alias in OAuth2 scopes documentation

---

Dockerfile
Dockerfile-alpine
Dockerfile-e2e

Update dockerfiles to latest alpine and golang

---

client/handler.go
cypress/integration/admin/client_create.js

When a client is created the client secret generation should be the same for api and cli
While trying to test the admin interface we recognized there are no tests for the handler. With the client_create.js admin cypress test this done. Did we miss a better part to test the admin handler?

handler: use generate secrets function as used in cmd 

---

consent/handler.go

fix spelling
Fix usage of "an" and "a" for correct spelling
no tests because no functional change, just documentation

consent: Update documentation

---

cmd/server/handler.go

#1680
#1685
Fix logging Span ID.
#1685 has mistake that `span_id` overwrites `trace_id`.
Now both `span_id` and `trace_id` are logged.
```
INFO[0030] started handling request                      method=GET remote="[::1]:59642" request=/health/alive span_id=00f067aa0ba902b7 trace_id=4bf92f3577b34da6a3ce929d0e0e4736
INFO[0030] completed handling request                    measure#hydra/admin: https://localhost:4444/.latency=77569 method=GET remote="[::1]:59642" request=/health/alive span_id=00f067aa0ba902b7 status=200 text_status=OK took="77.569µs" trace_id=4bf92f3577b34da6a3ce929d0e0e4736
```
I'm sorry...

cmd: Fix logging Span ID

---

client/manager_memory.go
client/manager_test.go
client/manager_test_helpers.go

Fix different behaviour between `memory client update manager` and `database client update manager`. 
If hydra runs with memory manager the update client operation only updates the forwarded values. If hydra runs with database manager the update client operation updates all fields of the client. If you don't forward a value for a given field the field is emptied in the database.

client: remove merge client during update

---

consent/manager_memory.go

[#1721](https://github.com/ory/hydra/issues/1721)
@aeneasr 
Fix `fatal error: concurrent map iteration and map write` by wrapping read part with lock.
- [ x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
- [ x] I have read the [security policy](../security/policy)
- [x ] I confirm that this pull request does not address a security vulnerability. If this pull request addresses a security
- [ x] I have added necessary documentation within the code base (if appropriate)
- [x ] I have documented my changes in the [developer guide](https://github.com/ory/docs) (if appropriate)
@aeneasr I was trying to add tests to catch …

consent: Fix concurrent write and read on map(#1721)

---

cmd/cli/handler_jwk.go
cmd/cli/handler_jwk_test.go

When using the ```keys import cli``` feature to import a JWK the ```alg``` field get lost during import.
As far as I can see the ```crypto/ecdsa```, ```crypto/elliptic``` and ```crypto/rsa``` structs for private and public keys, used by the ```github.com/mendsley/gojwk```, doesn't support a ```alg``` field. All my tests, trying to importing a non JWK, the ```alg``` field was empty.
I removed the ```github.com/mendsley/gojwk``` package and changed the ```toSDKFriendlyJSONWebKey``` function.

fix: When importing a JWK, the algorithm should be set

---

oauth2/handler.go

In `fosite` release `v0.30.3` the following method [was deprecated](https://github.com/ory/fosite/compare/v0.30.2...v0.30.3):
```go
// Deprecated: Use ExactOne, Matches or MatchesExact
func (r Arguments) Exact(name string) bool {
return name == strings.Join(r, " ")
}
```
Which caused the linter to fail.

chore: fix linter due to deprecation notice on 'func (r Arguments) Exact(name string) bool'

---

go.mod
go.sum
oauth2/fosite_store_sql.go
oauth2/oauth2_auth_code_test.go
oauth2/oauth2_refresh_token_test.go

- https://github.com/ory/hydra/issues/1719
- https://github.com/ory/hydra/issues/1735
_(Each of the packages above will need a new tag release once/if the PRs have been merged)_ 🙏 
To improve consistency in certain authorization flows that utilize transactions, this PR forces the SQL storage transaction isolation level to `LevelRepeatableRead`. This will ensure that we avoid the phenomena of non-repeatable reads which occur when a transaction re-reads data it has previously read and then finds out that another transaction has since modified that data and committed. As a result, setting this isolation level fixes a flaw where one could use a given refresh token more than once. See the test added.
In the event that multiple concurrent transactions are competing under a given refresh token …

fix: force transaction isolation level to `LevelRepeatableRead`

---

Dockerfile
Dockerfile-alpine

Go's netgo implementation currently does not respect hostname overrides
defined in /etc/hosts if the /etc/nsswitch.conf does not exists.
Made changes to the Dockerfiles to add a standard /etc/nsswitch.conf
to fix this issue.
No issue have been opened for this.
When hydra is being used in a form of a docker image in an environment where hostname overrides are being used through /etc/hosts the overrides are not respected. This is not an issue with hydra all, but a well known one with golang and alpine, as the alpine base image a few years ago got rid of the nsswitch.conf saying that it is not needed anymore. Unfortunately golang depends on the presence of this file and when it is missing it just ignores whatever is in the /etc/hosts file.
This change adds the nsswitch.conf back to the …

fix(docker): Add nsswitch.conf into the dockerfiles

---

.schema/api.swagger.json
.schema/config.schema.json
internal/httpclient/models/accept_consent_request.go
internal/httpclient/models/accept_login_request.go
internal/httpclient/models/consent_request.go
internal/httpclient/models/consent_request_session.go
internal/httpclient/models/flush_inactive_o_auth2_tokens_request.go
internal/httpclient/models/generic_error.go
internal/httpclient/models/health_not_ready_status.go
internal/httpclient/models/health_status.go
internal/httpclient/models/json_web_key.go
internal/httpclient/models/json_web_key_set.go
internal/httpclient/models/json_web_key_set_generator_request.go
internal/httpclient/models/login_request.go
internal/httpclient/models/logout_request.go
internal/httpclient/models/o_auth2_client.go
internal/httpclient/models/o_auth2_token_introspection.go
internal/httpclient/models/oauth2_token_response.go
internal/httpclient/models/open_id_connect_context.go
internal/httpclient/models/previous_consent_session.go
internal/httpclient/models/reject_request.go
internal/httpclient/models/userinfo_response.go
internal/httpclient/models/version.go
internal/httpclient/models/well_known.go

Because viper converts the type from both string and number to time.Duration we can allow both types.
closes #1811

fix: allow -1 as ttl.refresh_token value

---

.schema/config.schema.json
consent/helper.go
consent/helper_test.go
consent/strategy_default.go
docs/docs/advanced.md
docs/docs/reference/configuration.md
driver/configuration/provider.go
driver/configuration/provider_viper.go
driver/configuration/provider_viper_test.go
go.mod
internal/.hydra.yaml
internal/config/config.yaml

Closes #1753 as discussed with @aeneasr.
Implements the workaround from https://web.dev/samesite-cookie-recipes/ for the CSRF cookies only when using SameSite=None. This is configurable and disabled by default.
Also adds some unit tests for the existing CSRF cookie helpers, along with unit tests for this change.
- [xI confirm that this pull request does not address a security
the changes.
works.
Regenerating the documentation changed quite a few bits in the configuration section that were unrelated to my change. Please double check those changes 😬

feat: Add workaround for CSRF SameSite=None cookies

---

.schema/config.schema.json
driver/configuration/provider_viper_test.go
internal/.hydra.yaml

Configuration JSON schema did not include `strategies.access_token`.
the changes.
works.

strategies.access_token missing in configuration JSON schema

---

docs/versioned_docs/version-v1.5/debugging.mdx

Issue I experienced today, running Hydra 1.4.10 in dangerous HTTP mode, the CSRF cookie defaulted to SameSite=None, but the cookie was not marked as secure (which makes sense, as Hydra is running over HTTP), so the cookie gets ignored (and was getting CSRF value not present errors).
I was able to get around it by either overriding the SameSite setting, or by switching to TLS termination.
Additional line in the docs about CSRF issues if SameSite=None and running over HTTP (the cookie won't be marked as Secure, and modern browsers such as Chrome will just ignore the cookie)
the changes.
works.

docs: Adding details about CSRF cookie problems

---

docs/docs/advanced.md

Documentation is missing informailtion about auth for /oauth2/revoke endpoint and it conused 
the changes.
works.

docs: Adding details about auth creds in body

---

Makefile
docs/docs/install.md

Closes #1857
Fix the build from source by adding packr2 steps.
the changes.
works.

fix: add packr2 steps in Makefile

---

persistence/sql/migrations/20200521071434_consent.cockroach.down.sql
persistence/sql/migrations/20200521071434_consent.cockroach.up.sql
persistence/sql/migrations/20200521071434_consent.mysql.down.sql
persistence/sql/migrations/20200521071434_consent.mysql.up.sql
persistence/sql/migrations/20200521071434_consent.postgres.down.sql
persistence/sql/migrations/20200521071434_consent.postgres.up.sql

Add an index over subject and client_id in order to avoid the
(sometimes) underperformant zigzag join query.
Closes #1789
Related to #1755 https://github.com/cockroachdb/cockroach/issues/47179
After applying the proposed index, the query plan now avoids the zigzag join query, reducing the query times from 50s to 2s in worst cases in my tests.
```
distributed	true
vectorized	false
sort		
│	order	-requested_at
└── render		
└── lookup-join		
│	table	hydra_oauth2_consent_request_handled@primary
│	type	inner
│	equality	(challenge) = (challenge)
│	equality cols are key	
│	parallel	
│	pred	"(@9 = '{}') AND (@7 = true)"
└── filter		
│	filter	skip = false
└── index-join		
│	table	hydra_oauth2_consent_request@primary
└── scan		
table	hydra_oauth2_consent_request@hydra_oauth2_consent_request_client_i …
```

fix: consent cockroachdb perfomance issue with zigzag join query 

---

.circleci/config.yml

CI job `nancy/test` fails if hydra has vulnerable dependencies.
Developers should fix it if it's possible but it's not always possible.
Then I changed workflow to start `test` regardless of `nancy/test` result.
the changes.
works.

ci: Make test independent from Nancy

---

docs/docs/advanced.md

Add hint to allow login provider login different subject when there is already an authentication of another subject.
the changes.
works.

docs: add hint for login different subject

---

oauth2/handler.go
oauth2/handler_test.go

Here is the issue that this PR is trying to fix `/userinfo endpoint misses www-authenticate header for 401 response` #1827
As far as I understood, apparently there are two cases that `/userinfo` API returns 401 error. One is if introspection API returns 401 and the other one is if token type is not `fosite.AccessToken`. Thus, I covered these two cases by adding `www-authenticate` header with reason coming from `RFC6749Error`
I've also added a new test case but needed small changes to make it happen.
This is my first PR, and I'm not familiar with the codebase. I'd be glad to hear better ways to do these changes if any.
[security@ory.sh](mailto:security@ory.sh)) from the …

oauth2: add www-authenticate header in case of unauthorized error for userinfo endpoint

---

oauth2/handler.go
x/errors.go
x/errors_test.go

Log errors with request information.
```
$ DSN=memory LOG_LEVEL=info go run main.go serve all
```
Currently, error log doesn't include request information.
```
$ curl -k -X POST "https://localhost:4444/oauth2/token?bar=foo" -H 'Traceparent: 00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01'
ERRO[2020-06-05T15:13:43+09:00] An error occurred                             audience=application error=map[message:invalid_request reason:The POST body can not be empty. status:Bad Request status_code:400] service_name= service_version=
```
By this PR, error log includes request information
```
$ curl -k -X POST "https://localhost:4444/oauth2/token?bar=foo" -H 'Traceparent: 00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01'
ERRO[2020-06-05T11:51:16+09:00] An error occurred …
```

feat: Error log with request information

---

cmd/cli/handler_helper.go
cmd/clients.go

Fixes #1230
This allows hydra commands such as `hydra clients` to set the endpoint to a unix socket
the changes.
works.

feat: Allow unix socket as --endpoint

---

consent/helper.go
consent/helper_test.go

Closes: #1907 
Enables legacy compatibility on iOS version < 13 and macOS version < 10.15
the changes.
works.
See #1907

fix: same site legacy workaround on iOS 12

---

.circleci/config.yml
Makefile

This install dependencies only when you make a target that needs it.
This also removes the check that certain system dependencies (e.g. go)
are installed. Instead, we simply let the target fail. This ensures we
only test for the desired dependencies.
Fixes #1916 
Since I don't have the dependencies installed, I'm relying on CI to tell me if this is working properly...
the changes.
works.

fix: Improve Makefile dependency management

---

.schema/config.schema.json
cmd/server/handler.go
docs/docs/production.md
driver/configuration/helper.go
driver/configuration/provider.go
driver/configuration/provider_viper.go
driver/configuration/provider_viper_test.go
internal/.hydra.yaml
internal/config/config.yaml

This allows the reverse proxy to actually read the unix socket, since
- The default permissions are 0755
- Hydra is usually run as a user different than the reverse proxy
- One needs read and write permissions to connect to the socket
With the commit, one can set the group to be a group that contains the
reverse proxy user and permissions to 0770
the changes.
works.

feat: Allow modifying unix socket permissions

---

.circleci/config.yml

Optimize CircleCI workflow to catch error and end faster.
CircleCI jobs work 4 jobs maximum at same time because of free OSS plan.
In hydra, there are 12 jobs to be kicked at created PR but actually just each random 4 jobs proceed.
I think there are 2 problems.
First, we cannot catch error faster if similar and long jobs such as `test-e2e-*` or `test-legacy-*` are kicked.
Second, error PR blocks other PR because concurrency limitation is shared. If on of `test-e2e-*` failed, others are likely to fail for same reason.
So I changed workflow like this
before
after
the changes.
works.

chore: Optimize CircleCI workflow

---

tracing/middleware.go
tracing/middleware_test.go

https://github.com/ory/hydra/issues/1924
Disable tracing for health endpoints
the changes.
works.

feat: Disable tracing for health endpoints

---

consent/strategy_default.go
consent/strategy_default_test.go

Simple nitpick to correct a copy/paste error in the error_hint during a failed logout flow (now, with a corrected test case, too ;-) )

fix: logout error hint

---

Makefile
consent/sdk_test.go
consent/strategy_default_test.go
consent/strategy_helper_test.go
internal/httpclient/models/completed_request.go
internal/httpclient/models/consent_request.go
internal/httpclient/models/login_request.go
internal/httpclient/models/reject_request.go
oauth2/oauth2_auth_code_test.go
test/mock-lcp/main.go

Fix SDK generation at Makefile because of many unexpected diff.
I referred to `ory/sdk`.
https://circleci.com/orbs/registry/orb/ory/sdk#orb-source
the changes.
works.
This PR includes some diff at SDK. Is it expected behavior?

fix: SDK generation at Makefile

---

.schema/api.swagger.json
consent/doc.go
consent/handler.go
consent/sdk_test.go
cypress/integration/oauth2/consent.js
internal/httpclient/client/admin/revoke_consent_sessions_parameters.go

close #1951
Revokes all consent sessions of a subject only if `client` URL parameter is set `all` value.
An error returns if it's called without `client` URL parameter.
the changes.
works.

fix: Revokes all consent sessions of a subject only if explicitly requested

---

driver/cors.go
driver/cors_test.go

#1754 
This change was originally intended to fix the issue described in the bug. However, I am not able to repro it as shown in the newly added test.
the changes.
works.
- [N/A] I have added or changed [the documentation](docs/docs).
I removed many extra loops for validating the origin against the CORS allowlist. The viper config was shared across test cases causing dependency on the order of the test cases. It also hid some assumptions about the setup.

refactor: cleanup the code for CORS handling

---

.circleci/config.yml
.schema/config.schema.json
.schema/version.schema.json

prepares #1986 
Analogously to kratos this adds:
- config top level version key
- ory/goreleaser/render-version-schema automation
- the version schema itself
When this is merged we can make a PR to schemastore.org

feat: add and automate version schema

---

.github/pull_request_template.md
.github/workflows/closed_references.yml
README.md
docs/docs/contributing.md

Updated repository templates to https://github.com/ory/meta/commit/edcdd4b05620b87c771b7876792d5066b8b3bcc3.

chore: update repository template to edcdd4b0

---

.schema/version.schema.json

Rendering the version schema and pushing it failed during the release in CCI. This is the commit that was not pushed. The automation is updated independently.
Add the latest release to the version schema.
This commit comes from CCI.

autogen: add v1.7.4 to version.schema.json

---

docs/docs/limitations.md

It said "an maximum" but I believe it should be "a maximum".

docs: minor text typo for limitations.md

---

oauth2/handler.go

[#2031](https://github.com/ory/hydra/issues/2031)
Invalid credentials or an expired token is a normal thing to happen and should be logged on "info" level, not on "error" level as is currently the case.
the changes.
works.

WIP: Downgrade log level for access rejections as a consequence of invalid credentials/expired token

---

.github/workflows/closed_references.yml
README.md
docs/docs/contributing.md
internal/httpclient/client/admin/delete_o_auth2_token_responses.go

Updated repository templates to https://github.com/ory/meta/commit/92ae8b93c03738d00573f229a412f9eac7a71a99.

chore: update repository template to 92ae8b93

---

test/e2e/Dockerfile-e2e-env
test/e2e/README.md

The file and build pipeline have moved to https://github.com/ory/e2e-env.
the changes.
works.

fix: remove docker-e2e file

---

cmd/serve.go

#2065 
Fixed broken link to config docs displayed on `hydra serve` help following the recommendations from @tacurran.
the changes.
works.

docs: fixed broken link to config docs displayed on hydra serve help

---

.github/workflows/closed_references.yml
CONTRIBUTING.md
README.md
SECURITY.md
docs/docs/contributing.md

Updated repository templates to https://github.com/ory/meta/commit/6f3059720c2206a267a4e511cc149439a9a90906.

chore: update repository template to 6f305972

---

README.md

Remove www from the pkg.go.dev path used for the Go documentation badge. https://pkg.go.dev/www.github.com/ory/hydra doesn't route to the hydra documentation while https://pkg.go.dev/github.com/ory/hydra does.
the changes.
works.

docs: Update PkgGoDev link in README.md

---

cmd/server/handler.go
driver/registry_base.go
metrics/prometheus/doc.go
metrics/prometheus/metrics.go
x/tls_termination.go
x/tls_termination_test.go

The purpose of this PR is to allow /metrics/prometheus endpoint to be invoked without https or x-forwarded-proto: https header.
In some cases prometheus is already in cluster behind LBS and (without a lot of hassle) it does not set this header.
changes:
- moved MetricsPrometheusPath constant to metrics/prometheus/metrics.go
- added rule to allow insecure requests for MetricsPrometheusPath endpoint (the same as for health routes)
- arranged tls_termination_test.go test to cover all cases in RejectInsecureRequests function
relates to issue #2072
@aeneasr , please take a look at this PR
the changes. …

feat: metrics prometheus endpoint should not require x-forwarded-proto header

---

.github/workflows/closed_references.yml
.reference-ignore
docs/docs/contributing.md

Updated repository templates to https://github.com/ory/meta/commit/bf0b087e8893145e2067664515b1a75cb45fb92e.

chore: update repository template to bf0b087e

---

docs/docs/advanced.md
docs/versioned_docs/version-v1.4/advanced.md
docs/versioned_docs/version-v1.5/advanced.md
docs/versioned_docs/version-v1.6/advanced.md
docs/versioned_docs/version-v1.7/advanced.md

If necessary I can file a new issue for this work but I felt it was not necessary given how simple the fix is.
Fixed a typo on the "Advanced OAuth2 and OpenID Connect Flows" (`s/pariwise/pairwise/`).
the changes.
works.

docs: fix typo "pariwise" on advanced flows page

---

Dockerfile
Dockerfile-alpine
Dockerfile-e2e

Updated dockerfile-e2e to use golang 1.15.2 now that 1.13 is EOL. Updated other dockerfiles to use Alpine 3.12 to make all dockerfile consitant.
- [x ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ x] I have read the [security policy](../security/policy).
- [x ] I confirm that this pull request does not address a security
the changes.
works.

fix: updated to golang 1.15.2 and consitant alpine 3.12

---

consent/strategy_default_test.go

And fixed assert.EqualError params in right order in TestStrategyLoginConsent
The merge request does not relate to any issue, just fix confusing things in tests
The merge request does not propose any change.
the changes.
works.
In the test `TestStrategyLoginConsent` we have the couple lines of code:
```go
c, err := strategy.HandleOAuth2AuthorizationRequest(w, r, &tc.req)
t.Logf("DefaultStrategy returned at call %d:\n\tgot: %+v\n\texpected: %s", calls, c, err)
```
The "got" and "expected" in this log confusing the developer because it just "result" and "err" returned from …

test: fix confusing expected/got

---

client/client.go
client/client_test.go
client/handler.go
client/manager_test_helpers.go
client/validator.go
client/validator_test.go
consent/handler_test.go
consent/manager_test_helpers.go
consent/sdk_test.go
consent/strategy_default.go
consent/strategy_default_test.go
consent/subject_identifier_algorithm_pairwise.go
consent/types.go
docs/config.js
docs/docs/configure-deploy.mdx
driver/cors_test.go
go.mod
go.sum
internal/fizzmigrate/consent/x_manager_sql_migrations_test.go
internal/fosite_store.go
oauth2/fosite_store_helpers.go
oauth2/fosite_store_test.go
oauth2/handler_test.go
oauth2/oauth2_auth_code_test.go
oauth2/oauth2_client_credentials_test.go
oauth2/oauth2_refresh_token_test.go
persistence/sql/migratest/exptected_data.go
persistence/sql/migratest/migration_test.go
persistence/sql/persister_client.go
persistence/sql/persister_test.go

closes #2148
Upstream dependency: https://github.com/gobuffalo/pop/pull/604

fix: client update breaks primary key

---

.circleci/config.yml
cypress/helpers/index.js
cypress/integration/admin/client_create.js
cypress/integration/oauth2/authorize_code.js
cypress/integration/oauth2/authorize_error.js
cypress/integration/oauth2/client_creds.js
cypress/integration/oauth2/consent.js
cypress/integration/oauth2/introspect.js
cypress/integration/oauth2/jwt.js
cypress/integration/oauth2/refresh_token.js
cypress/integration/openid/authorize_code.js
cypress/integration/openid/logout.js
cypress/integration/openid/prompt.js
cypress/integration/openid/revoke.js
cypress/integration/openid/userinfo.js
cypress/plugins/index.js
cypress/support/commands.js
cypress/support/index.js
package-lock.json
package.json
test/e2e/oauth2-client/src/index.js

This enforces `ory-prettier-styles` for cypress tests. The format is now also checked in the cci/validate task.

chore: apply ory-prettier-styles to cypress tests

---

consent/strategy_default.go
consent/strategy_default_test.go

I didn't open an issue because I prefer to directly show the problem by submitting a PoC.
Using `state` in the logout flow is optional, so `state` can be
empty. In order to avoid an ugly `/post-logout-redirect-uri?state=`
URI, the state should only be appended if it is not empty.
Relevant specification: https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout
the changes.
works.
If you are willing to accept this change, I'll add tests (and fix the typo in the commit).

feat: Only pass state if it was set

---

.github/semantic.yml
CONTRIBUTING.md
docs/docs/contributing.md

Updated repository templates to https://github.com/ory/meta/commit/781e8fb26afe90cedb50a939ad3fb6fa3798eefd.

chore: update repository template to 781e8fb2

---

docs/docs/contributing.md

Updated repository templates to https://github.com/ory/meta/commit/8042a8da0b42c9ff50deb9860249f95c756af18f.

chore: update repository template to 8042a8da

---

docs/docs/debug.mdx
docs/versioned_docs/version-v1.9/debug.mdx

Fixed document describe error.
> The OAuth 2.0 Client making the request is not allowed to request the scope `openid`
Should be `refresh_token`, according [here](https://github.com/ory/fosite/blob/master/handler/oauth2/flow_authorize_code_token.go#L129)
```go
func canIssueRefreshToken(c *AuthorizeExplicitGrantHandler, request fosite.Requester) bool {
// Require one of the refresh token scopes, if set.GetGrantTypes
if len(c.RefreshTokenScopes) > 0 && !request.GetGrantedScopes().HasOneOf(c.RefreshTokenScopes...) {
return false
}
// Do not issue a refresh token to clients that cannot use the refresh token grant type.
if !request.GetClient().GetGrantTypes().Has("refresh_token") {
return false
}
return true
}
```

fix: document describe error

---

quickstart.yml

#2213 
Remove this entry. I couldn't find any reason for this to be there. No indentation of volumes identified nor anything else associable
the changes.
works.
- [N/A] I have added or changed [the documentation](docs/docs).
This will render docker-compose compatible format of quickstart.yml.
additionaly version of `oryd/hydra-login-consent-node` is not existing.

Removing unrelated entry

---

.github/ISSUE_TEMPLATE/config.yml
CONTRIBUTING.md
docs/docs/contributing.md

Updated repository templates to https://github.com/ory/meta/commit/3193a1c149e88bd322dde3e813f2ada23b32709d.

chore: update repository template to 3193a1c1

---

docs/versioned_docs/version-v1.9/guides/login.mdx

This PR corrects the link of the first note in https://www.ory.sh/hydra/docs/guides/concepts/login
to https://www.ory.sh/hydra/docs/concepts/login
the changes.
works.

docs: corrected a link within the docs

---

docs/versioned_docs/version-v1.8/configure-deploy.mdx

Changed the fallback url as proposed in #2254.
Since OAUTH2_ERROR_URL is deprecated.
It should not be changed for the 1.8. docs, correct?
closes #2254
the changes.
works.

docs: change deprecated fallback url

---

README.md

Updated repository templates to https://github.com/ory/meta/commit/6aa9dbbf3cd126373bee21c096d05763f9961a4e.

chore: update repository template to 6aa9dbbf

---

CONTRIBUTING.md
docs/docs/contributing.md

Updated repository templates to https://github.com/ory/meta/commit/bb146082236a7bbb94c3e042951b937aa76d25a4.

chore: update repository template to bb146082

---

docs/sidebar.json
docs/versioned_sidebars/version-v1.9-sidebars.json

Moved the FAQ section from `further reading` to `debug&help` since it is mostly about issues that arise during setup or production. 
Personally I would consult `further reading` only when I have read everything else, am bored, or really want to know every detail. It is not a place where I would look for frequently asked questions.
We can certainly improve the FAQ system overall, it is a work in progress. But for the time being I think its ok to have the FAQ in `debug&help`

docs:move faq sidebar

---

metrics/prometheus/metrics.go
metrics/prometheus/middleware.go

Currently, Kratos emits response time metrics that can be used to monitor latency as well as Requests Per Second. [Kratos's metrics middleware](https://github.com/ory/kratos/blob/master/metrics/prometheus/middleware.go#L19-L23) looks like:
```
func (pmm *MetricsManager) ServeHTTP(rw http.ResponseWriter, r *http.Request, next http.HandlerFunc) {
start := time.Now()
next(rw, r)
pmm.prometheusMetrics.ResponseTime.WithLabelValues(r.URL.Path).Observe(time.Since(start).Seconds())
}
```
Currently, the equivalent in Hydra omits the first and last lines:
```
func (pmm *MetricsManager) ServeHTTP(rw http.ResponseWriter, r *http.Request, next http.HandlerFunc) {
next(rw, r)
}
```
Consequently, Hydra doesn't emit the response time metrics that would enable us to monitor latency/RPS. 
In our case, …

feat: Enable emittance of response time metrics (achieving parity with Kratos)

---

docs/docs/5min-tutorial.mdx
docs/versioned_docs/version-v1.9/5min-tutorial.mdx

Added the qu ickstart config to the doc, short explanation where to find the config and how its loaded into docker. 
also a few comments in the yaml itself. 
It did not fit quite into the quickstart, so I just added it to the bottom. 
Let me know what should be changed or further improved, if needed.
the changes.
works.

docs: quickstart config

---

.schema/config.schema.json

I made a mistake in previous pull request, these socket mode values are in decimal, not octal format. Sorry.

fix: Revert mode default and maximum values

---

.schema/config.schema.json

Move from viper to koanf caused env vars without corresponding
paths in config.schema.json to be ignored. This commit adds
missing sqa section, so the SQA_OPT_OUT env var has effect again.
Closes: #2358
the changes.
works.

fix: adds sqa section to config.schema.json

---

docs/docs/guides/kubernetes-helm-chart.mdx
docs/versioned_docs/version-v1.9/guides/kubernetes-helm-chart.mdx

Tried example with helm 3.5.2 and it does not support `--name` flag. So I moved name and repository to first line of commands.
the changes.
works.

docs: update examples to new helm install command format

---

driver/registry_base.go
driver/registry_base_test.go

#2338
In the event of a general network error, avoid logging a misleading/confusing message.
the changes.
works.

fix: Add network specific error message to avoid confusion

---

README.md

Update the README.md file with the correct test commands as the previous ones were incomplete or out dated.
the changes.
works.

docs: improve readme tests section

---

docs/docs/advanced.md
docs/versioned_docs/version-v1.9/advanced.md

On https://www.ory.sh/hydra/docs/reference/configuration/ under 'subject identifiers' the name for defining which subject identifier algorithms are supported it is called "supported_types", not "enabled" as in these pages.
Testing shows that "supported_types" is the correct value for use in Hydra.
No related issue
Update documentation page to match reality
the changes.
works.
The page I have made a change to created some confusion when we enabled pairwise subject identifiers.
I don't care to read all the policies, as it is a miniscule change. Sorry.

docs: Fix subject identifier algorithms to match configuration

---

docs/docs/sdk/go.md
docs/versioned_docs/version-v1.9/sdk/go.md

the examples were a bit confusing, because the hydra-client was named `admin` - which conflicts with the correct import for the `admin.NewCreateOAuth2ClientParams` call.
i had to battle a bit around, and tried to rename a few variables and added correct imports, so the examples should just work when copy & pasting

fixed basic examples for the golang SDK

---

cypress/integration/oauth2/jwt.js
cypress/integration/oauth2/refresh_token.js
cypress/support/commands.js
go.mod
go.sum
oauth2/fosite_store_helpers.go
oauth2/oauth2_auth_code_test.go
oauth2/oauth2_refresh_token_test.go
persistence/sql/persister_oauth2.go
test/e2e/oauth2-client/src/index.js

Closes #2022
This PR leverages support for Refresh Token reuse Detection added in https://github.com/ory/fosite/pull/567. It makes hydra's `Persister` stop deleting refresh tokens, but deactivating them similar to whats done for authorization codes.
Modules need to be updated if PR for fosite gets merged.
the changes.
works.
See https://github.com/ory/fosite/pull/567 for fosite PR.

feat: Refresh Token Reuse Detection

---

driver/config/provider.go
oauth2/handler.go
oauth2/session.go
spec/config.json

[1542](https://github.com/ory/hydra/issues/1542)
Enable "nbf" (not before) claim to be optional as part of Access Token. This is compatible given the existing standard.
the changes.
works.
Unsure where I should append the required tests, please advice. Executed all tests as part of package of `oauth2`.

feat: Enable "nbf" (not before) claim to be optional for Access Token

---

consent/handler.go
driver/config/provider.go
driver/config/provider_test.go

#2422 
Use `urls.self.public` where possible and given, falling back to `urls.self.issuer`. Well-known URLs are continue to use `urls.self.issuer`.
the changes.
works.

fix: Use PublicURL where given

---

oauth2/handler.go

Just a small fix to get rid of non-standard `error_hint`.
the changes.
works.

fix: Do not use error_hint anymore

---

cmd/token_user.go

See thread: https://ory-community.slack.com/archives/C012RBW0F18/p1618883706197100
the changes.
works.

fix: Make token user command work with public clients

---

docs/docs/guides/login.mdx
docs/versioned_docs/version-v1.10/guides/login.mdx

Currently, I receive a 404 error if I want to be redirected to 'Login flow page' via this link, this PR fix it
the changes.
works.

fix: link in documentation

---

docs/docs/guides/kubernetes-helm-chart.mdx
docs/versioned_docs/version-v1.10/guides/kubernetes-helm-chart.mdx
docs/versioned_docs/version-v1.9/guides/kubernetes-helm-chart.mdx

https://github.com/ory/docs/issues/391
the changes.
works.

chore: fix links

---

driver/config/provider_test.go
go.mod
go.sum
internal/.hydra.yaml
internal/config/config.yaml
spec/config.json

#2447 
Integration with this change [feat: [Jaeger] Add maxTagValueLength for the feature request #2447](https://github.com/ory/x/pull/327) and make it configurable in ory/hydra. 
the changes.
works.

feat: Add the MaxTagValueLength config for jaeger of tracing

---

cmd/root.go

#2520
It looks like the `clientCmd.AddCommand(NewKeysImportCmd())` line was missed during a recent refactor, I just added it.
- [x ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
I looked briefly at adding tests but it looked like it would require some refactoring of the current strategy. If you would like me to look into it I can spend some time on it.

fix: add the missing keys import command

---

oauth2/handler.go
oauth2/handler_test.go

Fixing the header value based on the spec.
the changes.
works.

fix: Fixed WWW-Authenticate header in userinfo handler

---

oauth2/handler.go
oauth2/handler_test.go

[The spec](https://openid.net/specs/openid-connect-core-1_0.html#UserInfo) says:
> The aud value SHOULD be or include the RP's Client ID value. 
So this makes sure client ID is always there. It is true though that that section talks only about the situation when response is signed.
the changes.
works.

fix: Audience should include client ID

---

CONTRIBUTING.md
docs/docs/contributing.md

Updated repository templates to https://github.com/ory/meta/commit/4bad4b1b28491df76013a0a5c7da0b294a81ec7b.

chore: update repository template to 4bad4b1b

---

CONTRIBUTING.md
docs/docs/contributing.md

Updated repository templates to https://github.com/ory/meta/commit/b66d1cbe843bbf0e72e40d066190c0fe5451e2b5.

chore: update repository template to b66d1cbe

---

oauth2/doc.go
oauth2/handler.go
oauth2/handler_test.go

#2311 - wellknown is missing pkce related info
adds additional parameters to wellknown response as defined in RFC 8414
the changes.
works.

closes #2311 - wellknown is missing pkce related info

---

.github/pull_request_template.md
CONTRIBUTING.md
docs/docs/contributing.md
internal/httpclient/models/plugin_config_interface.go
internal/httpclient/models/volume.go
spec/api.json

Updated repository templates to https://github.com/ory/meta/commit/8565f4962a513e41152641aec96c303bb85057c6.

chore: update repository template to 8565f496

---

spec/config.json

>So the line that says "cert - Configures the private key" in the example config file is incorrect. It should be changed to read "Configures the certificate" or possibly "Configures the public certificate".
Thanks a lot for spotting and basically fixing this,  @pha3z
https://github.com/ory/hydra/discussions/2587

fix: parameter for Private Key in config

---

docs/docs/index.md

Just small change so it looks uniform for all projects in ory.sh/docs
```
Ory Hydra:
- Introduction 
- Introduction
```
instead of 
```
Ory Hydra:
- Introduction 
- ORY Hydra
```

chore: docs sidebar uniform

---

docs/docs/5min-tutorial.mdx
docs/versioned_docs/version-v1.10/5min-tutorial.mdx
docs/versioned_docs/version-v1.9/5min-tutorial.mdx

fix: correct CodeFromRemote syntax
https://github.com/ory/hydra/commit/df50360343f94c1a5132c309790c75c4f1b65945
same as
https://github.com/ory/kratos/pull/1490#discussion_r666167642
edit: my bad was just the codefromremote
the changes.
works.

fix: correct CodeFromRemote syntax

---

docs/docs/faq.md
docs/docs/limitations.md

docs: fix typo ('ROCP' to 'ROPC')

---

docs/docs/5min-tutorial.mdx
docs/versioned_docs/version-v1.10/5min-tutorial.mdx

Hi
Short flag like `-g` are handy in an interactive context when a veteran user has to type long commands again and again.
Here, this tutorial is a entry point for someone discovering the `hydra` CLI and it's not obvious yet that it refers the to `--grant-types`.
Also it's more consistent with the following snippet on the same page that uses `--grant-types` explicitly.
Thanks

docs: add long flag --grant-types in 5min tutorial

---

go.mod
go.sum

Updating x/sys so that this project supports go 1.17.
More context: https://github.com/Homebrew/homebrew-core/pull/83413
Without this fix running a binary can cause a panic, see upstream go issue: https://github.com/golang/go/issues/45702
the changes.
works.

chore: Update x/sys to support go 1.17

---

client/handler.go
docs/docs/advanced.md

fix: update client filter to client_name

---

docs/versioned_docs/version-v1.10/guides/kubernetes-helm-chart.mdx

Below are the changes made under Examples section
1. from hydraAdminUrl=http://hydra-example-admin:4445/'  to hydraAdminUrl=http://hydra-example-admin/' as we don't expose port number when using URL and ingress and will take care of the mapping the port behind scenes
2. Changed from --set 'hydra.config.secrets.system=$(LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | base64 | head -c 32)' to --set 'hydra.config.secrets.system={'$(LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | base64 | head -c 32)'}' as hydra.config.secrets.system expects a list of strings, so embraced with curly braces so a random list of strings will be generated.
If we don't add the above 2nd change then it will result in error as `Error: execution error at (hydra/templates/secrets.yaml:16:22): Expected …

Updated Examples section part of the page

---

.github/workflows/stale.yml
docs/docs/guides/oauth2-token-introspection.mdx

Updated repository templates to https://github.com/ory/meta/commit/455ef8896cd7ddfa08f4c2b8325c528bcdb65762.

chore: update repository template to 455ef889

---

oauth2/hook.go
oauth2/oauth2_auth_code_test.go

Current implementation doesn't set this header which makes some servers reject the request.
#2649
the changes.
works.

fix: add content-type header to hook request

---

driver/registry_base.go

Replace `Fatalf()` with `Println()` to log when unable to initialize a tracer. This avoid unnecessary exits. ~~Additionally, total 3 attempts are made to init the tracer.~~
Fixes #2642 
CC: @aeneasr 
the changes.

Replace fatal error of jaeger initialization with print

---

cmd/keys_create.go
docs/docs/.static/api.json
docs/versioned_docs/version-v1.10/.static/api.json
docs/versioned_docs/version-v1.10/cli/hydra-keys-create.md
driver/registry_base.go
jwk/doc.go
jwk/manager_test_helpers.go
persistence/sql/persister_test.go
spec/api.json

Based on #628, but updated for `1.10.x`. As mentioned in #628, ES256 is already supported for signing tokens, but not for generating JWTs. Looks like #628 was merged into `0.9.x`, but was not ported/merged into `0.10.x`.
Closes #2453
the changes.
works.

feat: Support ES256 for Create JWT

---

.circleci/config.yml
docs/docs/guides/oauth2-public-spa-mobile.mdx
install.sh
internal/certification/scripts/configure.sh
internal/certification/scripts/install.sh
internal/certification/scripts/start.sh
internal/certification/scripts/update.sh
scripts/run-bench.sh
scripts/run-configuration.sh
test/conformance/ssl/generate.sh
test/conformance/start.sh

Add shellcheck to the ci pipeline for testing and security improvements.
Closes https://github.com/ory/hydra/issues/2832
the changes.
works.
I have confirmed that all the parts pointed out by shellcheck have been fixed in my local environment.
```
$ shellcheck ./**/*.sh
```

feat: add shellcheck to circleci

---

.docker/Dockerfile-alpine
.docker/Dockerfile-build
.docker/Dockerfile-scratch
.docker/Dockerfile-sqlite

Signed-off-by: Daniel Sutton <daniel@ducksecops.uk>
Updated Alpine 3.14.2 to 3.14.3 to solve several security issues
CVE-2021-42374,CVE-2021-42375,CVE-2021-42378,CVE-2021-42379,CVE-2021-42380,CVE-2021-42381,CVE-2021-42382,CVE-2021-42383,CVE-2021-42384,CVE-2021-42385,CVE-2021-42386
- [x ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x ] I am following the
- [x ] I have read the [security policy](../security/policy).
the changes.
works.

chore: bump aline to 3.14.3

---

client/handler.go
client/sdk_test.go

Fixes the bug reported in #2869 by checking if the PATCH actually changes the Client Secret before updating. If the secret has not changed, we clear it as expected by the `UpdateClient` function, so the original secret remains untouched.
#2869 
the changes.
works.

fix: patch should not reset client secret

---

driver/registry.go

This fix resolves #2337 and ensures the proper version number is included on the `/version` api endpoint. As per the discussion in the issue, it sources this data from `driver\config\buildinfo.go` and shows "master" when run locally / in docker.
#2337 
the changes.
- [-] I have added tests that prove my fix is effective or that my feature
works.
- [-] I have added or changed [the documentation](docs/docs).
I didn't add a test because I didn't see testing of the `/health` or `/version` …

fix: version info nil on version api endpoint

---

docs/docs/reference/configuration.md
quickstart-tracing.yml
spec/config.json

* https://github.com/ory/hydra/issues/2597
the changes.
works.
Fixes the issue of `otel` not being configurable as the value isn't allowed in providers enum. Also adds docs for otel tracing.

feat(docs): opentelemetry tracing

---

docs/docs/production.md

Just a PR as per invitation, to reflect the discussion at https://github.com/ory/hydra/discussions/2943#discussioncomment-1997531
Thanks!
the changes.

docs: recommend to start with one container in prod to complete first-time setup.

---

.github/workflows/ci.yaml

Due to how branch protection works, we can't push without a token that
has permissions to bypass branch protection. Hence, we revert back to
PATs here.
However, we also want to prevent triggering recursive workflow runs
which can potentially occur in commits originating from a non-GitHub
Actions actor. One possible workaround would be to add a `[skip ci]` to
the body in autogen commits. This prevents any workflow from triggering
on the commit. See: https://github.com/ory/ci/commit/849d2713e4b24ee3540b1f752ad1a4094d634e2f
Let me know what you think.

fix: revert back to PATs

---

.github/workflows/ci.yaml

Pass `swag-spec-location` to the `sdk-release` job.

fix: pass swag-spec-location to sdk-release

---

.github/workflows/ci.yaml

Updates the newsletter list IDs to the actual production one (from the
CIrcleCI config).

fix: update mailchimp list ids

---

.docker/Dockerfile-alpine
.docker/Dockerfile-build
.docker/Dockerfile-hsm
.docker/Dockerfile-scratch
.docker/Dockerfile-sqlite
test/conformance/Dockerfile
test/conformance/hydra/Dockerfile

* I have changed some issues that I have found with *hadolint*, like condense **RUN** commands, changed **ADD** with **COPY** [nr 7](https://res.cloudinary.com/snyk/image/upload/v1551798390/Docker_Image_Security_Best_Practices_.pdf).
* I also deleted some lines in ``` RUN apk add --no-cache``` since it [should](https://github.com/gliderlabs/docker-alpine/blob/master/docs/usage.md#disabling-cache) be okay that way.
the changes.
works.

refactor: Updated Dockerfiles

---

jwk/generator_test.go

The tests for jwk generators had a logic flip and checks were never executed. Fixed that and some basic test logic.
the changes.
works.

fix: jwk generator checks were never executed. fixed that and some checks.

---

.schema/openapi/patches/oauth2.yaml
Makefile
internal/httpclient-next/api/openapi.yaml
internal/httpclient-next/api_metadata.go
internal/httpclient-next/docs/InlineResponse200.md
internal/httpclient-next/docs/InlineResponse2001.md
internal/httpclient-next/docs/InlineResponse503.md
internal/httpclient-next/docs/MetadataApi.md
internal/httpclient-next/model_inline_response_200.go
internal/httpclient-next/model_inline_response_200_1.go
internal/httpclient-next/model_inline_response_503.go
spec/api.json

Closes #3058
the changes.
works.

fix(sdk): correct polymorph type for consent session

---

cypress/integration/admin/grant_jwtbearer.js
cypress/integration/oauth2/grant_jwtbearer.js
internal/httpclient-next/api/openapi.yaml
internal/httpclient-next/docs/AdminApi.md
internal/httpclient-next/docs/TrustJwtGrantIssuerBody.md
internal/httpclient-next/docs/TrustedJwtGrantIssuer.md
internal/httpclient-next/model_trust_jwt_grant_issuer_body.go
internal/httpclient-next/model_trusted_jwt_grant_issuer.go
internal/httpclient/models/trust_jwt_grant_issuer_body.go
internal/httpclient/models/trusted_jwt_grant_issuer.go
oauth2/fosite_store_helpers.go
oauth2/trust/doc.go
oauth2/trust/grant.go
oauth2/trust/handler.go
oauth2/trust/handler_test.go
oauth2/trust/manager.go
oauth2/trust/request.go
oauth2/trust/validator.go
oauth2/trust/validator_test.go
persistence/sql/migratest/testdata/20220328111500_testdata.sql
persistence/sql/migrations/20220328111500000000_support_any_subject_trusts.down.sql
persistence/sql/migrations/20220328111500000000_support_any_subject_trusts.sqlite.down.sql
persistence/sql/migrations/20220328111500000000_support_any_subject_trusts.sqlite.up.sql
persistence/sql/migrations/20220328111500000000_support_any_subject_trusts.up.sql
persistence/sql/persister_grant_jwk.go
spec/api.json
spec/swagger.json

Previously, a trust relationship had to be setup for every subject
before the issuer could sign a JWT token for it. This change will allow
setting up token services that can issue tokens with any value in the
subject field.
#2930
the changes.
works.
This PR adds a new field to the trust creation request called `allow_any_subject`, and as long as this flag is set to false (or unset), the trust relationship creation service will behave just like it did before this change: the `subject` field …

feat: add support for trust grants that can issue tokens for any subject

---

.schema/openapi/patches/oauth2.yaml
internal/httpclient-next/api/openapi.yaml
internal/httpclient-next/docs/ConsentRequestSession.md
internal/httpclient-next/model_consent_request_session.go
spec/api.json

Fixes generated oauth2 accept consent session models
Seems like a bug with the client generator but the upstream repository has an issue open about this since 2018.
Based on #3074, updated the patch to keep `type` but remove the `additionalProperties` field
#3058
https://github.com/ory/sdk/issues/12
#3074
the changes.
works.

Fix generated consent model

---

consent/strategy_default.go

This pull request adds minor logging improvements. 
- Successful back-channel logout request logging. This is useful for [#2844](https://github.com/ory/hydra/pull/2844) when `trigger_backchannel_logout=true`. ~~Additionally log `token`  for both success/failed responses.~~
- ~~ID token logging in `POST /oauth2/token` endpoint~~
the changes.
- [] I have added tests that prove my fix is effective or that my feature
works.
- [] I have added or changed [the documentation](docs/docs).

feat: backchannel request logging

---

cmd/cli/handler_janitor.go

in `janitor`, `driver.Init()` is called. Though this is already done in the `driver.factory`. 
the changes.
works.

Remove extraneous call to driver.init()

---

consent/strategy_default.go
internal/httpclient-next/api/openapi.yaml
internal/httpclient-next/api_public.go
internal/httpclient/client/public/public_client.go
oauth2/handler.go
spec/api.json
spec/swagger.json

This pull request introduces feature to execute backchannel logout asynchronously.
**Use case**: User should not have to wait for backchannel requests to finish (4x30sec, with potential connection timeout 1min on each request), when performing logout from all applications using GET /oauth2/sessions/logout or from specific application by using DELETE /oauth2/auth/sessions/consent?trigger_backchannel_logout=true (https://github.com/ory/hydra/pull/2844)
Will add configuration option if needed. …

feat: async backchannel logout

---

cmd/cli/handler_janitor.go
driver/registry.go
driver/registry_base_test.go
driver/registry_sql.go
driver/registry_sql_test.go
persistence/definitions.go
persistence/sql/persister.go

Fixes the Ping logic on the SQL registry
https://github.com/ory/hydra/issues/2734
the changes.
works.

Fix ping logic for SQL Registry

---

README.md

Fix link OIDC Certification image

---

client/handler.go

Fix swagger documentation of the OAuth2 / OpenID Dynamic Client registration.
The endpoint was specified at `/connect/register`, but Ory Hydra exposes it at `/oauth2/register`.
the changes.
works.
Once this PR is merged, the documentation should also be updated: [Ory Hydra docs](https://github.com/ory/docs/blob/master/docs/hydra/guides/openid-connect-dynamic-client-registration.mdx)
Will sign the CLA once clarified with my superior.

fix: swagger for dynamic client registration

---

driver/registry_base.go
health/handler_test.go

defines and implements the
healthcheck struct to create a
definitive wrapper around the healthx handlers
also adds a cors middleware wrapper
for http.Handler types withouth the
iface defaults (might need changing)
#2989  
the changes.
works.
Needed another PR due to a partially pushed (amended git commit) on the older branch that'd need a force push, hence this.

FIX: Add CORS healthcheck handlers for alive/ready

---

cmd/cli/handler_client.go
cmd/clients_create.go
cmd/clients_update.go

feat: add token_endpoint_auth_signing_alg to cli

---

driver/config/provider.go
driver/config/provider_test.go
oauth2/.snapshots/TestHandlerWellKnown-hsm_enabled=false.json
oauth2/.snapshots/TestHandlerWellKnown-hsm_enabled=true.json
oauth2/handler.go
oauth2/introspector_test.go
test/e2e/circle-ci.bash
test/e2e/docker-compose.yml
test/e2e/oauth2-client/src/index.js

BREAKING CHANGE: The `iss` (issuer) value no longer appends a trailing slash but instead uses the raw value set in the config.
Setting
```yaml
urls:
self:
issuer: https://auth.example.com
```
has changed
```patch
-  "iss": "https://auth.example.com/"
+  "iss": "https://auth.example.com"
```
To set a trailing slash make sure to set it in the config value:
```yaml
urls:
self:
issuer: https://auth.example.com/
```
Closes #1482

fix: support issuer with and without trailing slash

---

oauth2/hook.go
oauth2/oauth2_auth_code_test.go

The refresh token hook currently requires a 200 response code with an updated session payload. There is no way to permit the token refresh without overriding the session data. It's useful, however, to be able to use the token refresh hook in order to accept/reject token refreshes without the need to update the session data.
This adds the ability for the token refresh hook to return a `204 No Content` response code to indicate that the token refresh is permitted, but not to update the session data.
The documentation has also been updated with PR https://github.com/ory/docs/pull/863
#3082 
In the future, the token refresh hook request payload …

feat: add ability to allow token refresh from hook without overriding the session claims

---

oauth2/oauth2_auth_code_test.go
x/oauth2cors/cors.go
x/oauth2cors/cors_test.go

fix: client specific CORS

---

x/oauth2cors/cors.go
x/oauth2cors/cors_test.go

fix: backport fix for client specific CORS (#1754)

---

quickstart-tracing.yml

Correct the tracing service name environment variable in `quickstart-tracing.yml`.
While I believe this used to be specific to OTEL, it now appears to be
configurable "globally", according to `spec/config.json`.
N/A - documentation update.

Correct the tracing service name environment variable in `quickstart-tracing.yml`.

---

cmd/token_user.go

cmd + c doesn't end the process on macOS but ctrl + c does.

fix: updated process ending instructions

---

persistence/sql/persister_oauth2.go

Handle server error when refresh token requests come same time.
Hydra usually handles this as `ErrInactiveToken`. But sometimes, when requests come very bad timing, this will be `ErrServerError` with very poor error log (`{msg: 'An error occurred',  error: {debug: 'server_error', status: 'Internal Server Error'}}` ).
As stack trace log (debug mode), it turns out that `Persister.deleteSessionBySignature` returns `sqlconn` 's error without any handling.  If it's `forsite` 's error, fosite will handle error as `ErrInvalidRequest` at [RefreshTokenGrantHandler.handleRefreshTokenEndpointStorageError](https://github.com/ory/fosite/blob/16614014a42b3905d065188c8f1f45433c4353f9/handler/oauth2/flow_refresh.go#L235-L239).
<details>
<summary>StackTrace(debug mode)</summary>
``` …
```

fix: handle server error when refresh token requests come same time

---

oauth2/session.go
oauth2/session_custom_claims_test.go

allowed_top_level_claims were set to nil if claim was not present
When allowed_top_level_claims are configured, they are always present in the token, with value null if they were never set.
This PR  fixes this and adds a regression test
the changes.
works.

fix: allowed_top_level_claims default to nil

---

internal/httpclient/api_admin.go
internal/httpclient/api_metadata.go
internal/httpclient/api_v0alpha2.go

Fixes leftover formatting issues from when the SDK generator didn't format changes. This problem should no longer happen since https://github.com/ory/ci/pull/109 is shipped now.
the changes.
works.

chore: fix formatting

---

persistence/sql/src/20220210000001_nid/20220210000001000000_nid.postgres.up.sql

@aarmam This adds your migration fix to the source that is used to generate the migrations[1].
[1]: `make persistence/sql/migrations`
the changes.
works.

chore: backport migration fix to migration source

---

.github/ISSUE_TEMPLATE/BUG-REPORT.yml
.github/ISSUE_TEMPLATE/DESIGN-DOC.yml
.github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml
README.md

Rename Ory Cloud to the Ory Network and update service description in the Readme.

feat: renaming to Ory Network

---

oauth2/handler.go

Since the v2.0.1 update, the `oauth2_token_response` model has been renamed and updated to `o_auth2_token_exchange`. Along with that, an issue occurred where the `scope` field of the token response was expected to be of type `int` (for some reason) instead of `string` as it should be, based on [RFC 6749](https://www.rfc-editor.org/rfc/rfc6749.html#section-3.3) and [previous versions of hydra SDK](https://github.com/ory/sdk/tree/97372e5028598744784ed126129c16a012cac6d7).
As figured out by @aeneasr and @jonas-jonas in https://github.com/ory/sdk/pull/223, this problem seems to be caused by [handler.go#L827](https://github.com/ory/hydra/blob/925013e39508c22d1038560ef552a0764f2b0177/oauth2/handler.go#L827). As mentioned earlier, the scope field should be of type `string` instead of `int`, as …

fix: scope type should be string instead of int

---

internal/httpclient/api/openapi.yaml
internal/httpclient/api_o_auth2.go
internal/httpclient/docs/OAuth2Api.md
oauth2/handler.go
spec/api.json
spec/swagger.json

Supersedes #3261
the changes.
works.

fix: add `client_id` and `client_secret` to `revokeOAuth2Token`

---

oauth2/handler.go

Prevent multiple redirections to post logout url
#3342 
the changes.
works.

fix: prevent multiple redirections to post logout url

---

consent/handler.go
consent/manager.go
consent/manager_test_helpers.go
consent/sdk_test.go
internal/httpclient/api/openapi.yaml
internal/httpclient/api_o_auth2.go
internal/httpclient/docs/OAuth2Api.md
persistence/sql/persister_consent.go
spec/api.json
spec/swagger.json

This pull request introduces feature to list subject consent sessions by session id.
**Use case**:
When authentication is initiated without `prompt` parameter from **multiple** devices, we would like to distinguish in what session was the consent given.
**Current situation**:
GET [/oauth2/auth/sessions/consent](https://www.ory.sh/hydra/docs/reference/api/#operation/listSubjectConsentSessions) returns **single** consent and it references to the session id, where the consent was initially given. Furthermore if logout is performed from device initially gave the consent, the reference to login session id is cleared.
If  `prompt=consent` were to be used, separate consents with separate session id would be returned and you would not have same problems. So this endpoint behaves differently in …

feat: list consent sessions by session id

---

persistence/sql/migrations/20211019000001000001_merge_authentication_request_tables.cockroach.up.sql
persistence/sql/migrations/20211019000001000001_merge_authentication_request_tables.mysql.up.sql
persistence/sql/migrations/20211019000001000001_merge_authentication_request_tables.postgres.up.sql
persistence/sql/migrations/20211019000001000001_merge_authentication_request_tables.sqlite.up.sql

This patch includes SQL migrations targeting environments which have not yet migrated to Ory Hydra 2.0. It removes inconsistent records which resolves issues during the migrations process. Please be aware that some users might be affected by this change. They might need to re-authorize certain apps. However, most active records should not be affected by this.
Installations already on Ory Hydra 2.0 will not be affected by this change.
Closes #3346
the changes.
works.

fix: invalidate tokens with inconsistent state

---

Makefile

A problem with the way the Makefile currenly installs external dependencies is that each time any change happens in the Makefile, it re-installs all dependencies. This gets annoying in repos that see a lot of changes to their Makefiles. This PR installs dependencies only when really needed, i.e. when they aren't installed or when their required version changes.
the changes.
works.

chore: persistent dependency installation

---

hsm/manager_hsm.go
hsm/manager_hsm_test.go
jwk/handler_test.go
jwk/helper.go
jwk/helper_test.go

Similar refactoring for HSM key manager https://github.com/ory/hydra/commit/5e2ea0b6c65441983a7e85f9e8434f6068f4fcba otherwise /.well-known/jwks.json will show double public keys, when HSM enabled.
the changes.
works.

fix: no longer use separate `public` and `private` keys in HSM key manager

---

x/oauth2cors/cors.go
x/oauth2cors/cors_test.go

https://github.com/ory/hydra/issues/3456
the changes.
works.
-  ~I have added or changed [the documentation](https://github.com/ory/docs).~
This shouldn't impact security, as the existing mechanism for determining client id using `client_secret_basic` does not validate any authentication.

fix: support allowed_cors_origins with client_secret_post

---

consent/handler.go
consent/strategy.go
consent/strategy_default.go
consent/strategy_logout_test.go
oauth2/oauth2_helper_test.go

Added support to `revokeOAuth2LoginSessions` API to revoke a single session by a SessionID (`sid` claim in the id_token) and execute an OpenID Connect Back-channel logout.
https://github.com/ory/hydra/issues/3448
the changes.
works.

feat: add ability to revoke login sessions by SessionID

---

client/client.go

Closes #3420
the changes.
works.

fix: use correct default value

---

consent/strategy_default.go
consent/strategy_oauth_test.go
driver/config/provider.go
spec/config.json

Fixes https://github.com/ory/hydra/issues/3473
Adds a configuration of a session cookie path, for setups where Hydra is served through a shared domain.
the changes.
works.

feat: add session cookie path configuration

---

driver/registry_sql.go

This silences `sql-rows-next` spans in tracing, which don't have any real informational value but can make up a large portion of all spans.

fix: reduce SQL tracing noise

---

cmd/cmd_create_client.go
cmd/cmd_helper_client.go

Skip consent feature was released in v2.1.0, but is missing as an available flag in the CLI.
the changes.
works.

feat: add --skip-consent flag to hydra cli

---

driver/config/provider.go
driver/config/provider_test.go

fix: proper SameSite=None in dev mode

---

persistence/sql/persister_grant_jwk.go

No breaking change, just a fix
#3498 
the changes.
works.
None

fix: fixing persister_grant_jwk having an OR statement without bracket leading to not using the last part of the query

---

cmd/cmd_get_client.go

The --json option does not exist in the current version of hydra. The --format json option had been added in place of the --json option. However, the --json option was left in the example. So, I fixed it.
the changes.
works.

fix: oauth2-client get client: fix example --json option

---

cmd/server/handler.go

The excluded path is wrong
the changes.
works.

fix: disable health check request logs (admin)

---

cmd/server/handler.go
internal/config/config.yaml

Following https://github.com/ory/hydra/pull/3496, logs were reduce drastically.
The last unneeded logs are those generated when prometheus endpoint is scraped.
the changes.
works.

feat: add metrics to disabled access log

---

driver/registry.go
driver/registry_base.go
x/oauth2cors/cors.go
x/oauth2cors/cors_test.go

As client settings change over time, this should be fully hot-reloadable. Resolves regression of #1754 on Ory Network.

feat: hot-reload Oauth2 CORS settings

---

consent/handler.go
driver/factory.go
driver/registry.go
driver/registry_base.go
oauth2/handler.go
oauth2/oauth2_refresh_token_test.go
persistence/sql/persister_oauth2.go
x/events/events.go

This implements the following events from https://github.com/ory-corp/cloud/issues/4028:
OAuth2 & OIDC
- OIDC initiated login succeeded
- OIDC initiated login failed
- Consent granted & revoked
- Consent grant aborted
Machine activity: Tokens, Permission checks
OAuth2
- Access tokens created
- Access token not created
- Access token inspected
- Access token check with result
the changes.
works.

feat: add event tracing

---

.schema/config.schema.json
Makefile
cmd/cmd_list_clients.go
driver/config/provider.go
driver/config/provider_fosite.go
driver/config/provider_test.go
fositex/config.go
spec/config.json

Adds a `strategies.jwt.scope_claim` optional configuration property that controls how the scope claim is represented in JWT access tokens. It can be set to one of `list`, `string`, or `both`. `list` (the default behavior) matches the current behavior of using a `scp` claim that is an array of strings. `string` uses a `scope` claim as defined in [this RFC](https://datatracker.ietf.org/doc/html/rfc9068#section-2.2.3), a single space-delimited string. `both` will include both the `scp` and `scope` claim in the token.
#3524 
[security@ory.sh](mailto:security@ory.sh)) …

feat: support different jwt scope claim strategies

---

go.mod
jwk/handler.go

First-time generation of RSA keys can take upwards of 5 sec per key. This is a quick improvement to the first-call performance of this endpoint. Should help with tests timing out etc.

feat: parallel generation of JSON web key set

---

go.mod
go.sum

chore: replace fosite rewrite

---

persistence/sql/persister_client.go
persistence/sql/persister_oauth2.go
x/events/events.go

feat: add more resolution to events and collect client metrics

---

cmd/cli/handler_migrate.go
cmd/migrate_status.go
cmd/root.go

...with optional `--block` flag to wait for migrations to be finished by another instance

feat: add `hydra migrate status` subcommand

---

cmd/cmd_perform_authorization_code.go

Restore ability to override auth and token urls for exemplary app, looks like this was accidentally broken in the past.
the changes.
works.

fix: restore ability to override auth and token urls for exemplary app

---

oauth2/handler.go
oauth2/oauth2_auth_code_test.go

fix: add kid to verifiable credential header

---

oauth2/handler.go
oauth2/oauth2_auth_code_test.go
oauth2/verifiable_credentials.go

This PR implements the following tweaks to the format of the JWT:
* The JWT should have an `exp` claim.  
* The JWT should have an `nbf` claim in addition to `iat` (OK if these are the same)
* The top-level `sub` would have to be the `did:jwk` value.  But it's OK to have the real `sub` if it's inside `credentialSubject`.
* The `aud` claim should be deleted, since it represents the intended verifier, not the client to whom the VC is issued.  (An important difference from normal OIDC is that these are different!)  In the Webex case, it's OK, since the app issuing the VC is the same as the app verifying it.  But that's not true in general.
* The UserInfo claims (`email`, `email_verified`, `updated_at`) should be inside `vc.credentialSubject`.
---
For reference, an example JWT VC looks like …

fix: tweak the format of the verifiable credential JWT

---

persistence/sql/persister_nid_test.go

This fixes three dropped test `err` variables in the `persistence/sql` package.

persistence/sql: fix dropped errors

---

persistence/sql/migrations/20240104181300000001_jwk_index.down.sql
persistence/sql/migrations/20240104181300000001_jwk_index.up.sql

feat: add missing index for jwk table

---

cmd/cmd_create_client.go
cmd/cmd_helper_client.go

This PR allows setting the access token strategy using the Hydra CLI: `--access-token-strategy jwt`.
#3717
the changes.
works.

feat: add access token strategy parameter to cli

---

consent/strategy_default.go

According to the specification at https://openid.net/specs/openid-connect-backchannel-1_0.html#BCResponse the Relying Party must respond with a status code 200. However, it also notes that the OpenID Provider should be prepared to handle status code 204 (No Content) as a successful response as well.
This is a previously unknown bug.
Reproduction:
1. Configure backchannel logout
2. The relying party responds with a 204 status code on the backchannel logout request
3. Hydra logs an error
Note that this does not change any behaviour. The logged error does not have an influence whether the user is logged out or not.
vulnerability. If this pull request addresses a security vulnerability, …

fix: Backchannel Logout: Fix error log when RP responds with status code 204

---

oauth2/handler.go

fix: do not retry sending responses

---

cmd/cmd_get_client.go

👋 
This PR updates the example shown by `get oauth2-client` to show how to extract the client name rather than client secret, as the `.client_secret` property is never returned by this call which may result in some confusion.
- [] I have referenced an issue containing the design document if my change
the changes.
works.

docs: update doc example for get oauth2-client

---

jwk/manager.go
oauth2/fosite_store_helpers.go
persistence/sql/persister_grant_jwk.go
persistence/sql/persister_jwk.go
persistence/sql/persister_nid_test.go

GetPublicKeys used to fetch all keys in a set, even if they were actually not being used. This patch fixes that.
the changes.
works.

fix: faster GetPublicKeys

---

oauth2/handler.go

fix(docs): adjust note about SDK support on oauth2 flow endpoints

---

consent/strategy_oauth_test.go
oauth2/.snapshots/TestUnmarshalSession-v1.11.8.json
oauth2/.snapshots/TestUnmarshalSession-v1.11.9.json
oauth2/fixtures/v1.11.8-session.json
oauth2/fixtures/v1.11.9-session.json
oauth2/handler.go
oauth2/session.go
oauth2/session_test.go

Adding custom claims with numerical types (think JavaScript Number) previously did not
round-trip through Hydra correctly. For example, passing UNIX timestamps in custom claims
would end up as floating points in exponential notation in the final token. That, in turn,
confused or broke downstream consumers of the token, including Kratos.
Ref https://github.com/go-jose/go-jose/issues/144

fix: broken JSON round-tripping for custom claims

---

.docker/Dockerfile-build
.docker/Dockerfile-hsm
.github/workflows/ci.yaml
Makefile
README.md
scripts/db-diff.sh
test/conformance/hydra/Dockerfile
test/e2e/circle-ci.bash

Move from distroless/static-debian12 to distroless/base-nossl-debian12 to get fewer CVE alerts
Uses the technique described in https://www.arp242.net/static-go.html

chore: compile a static binary in Docker

---

consent/handler.go

This is not an issue, but the related discussions can be found below.
https://github.com/orgs/ory/discussions/118
the changes.
works.

fix: change comment on revokeOAuth2LoginSessions

---

.github/workflows/ci.yaml
.schema/config.schema.json
Makefile
cmd/cmd_perform_authorization_code.go
driver/config/provider.go
driver/config/serve.go
spec/config.json
x/int_to_bytes.go

This allows you to easily test an Authorization Code flow against hydra without having to have a consent UI otherwise available.
If you want to use the built-in UI, configure the login+consent UIs to point to the same server as the redirect URI:
```sh
ory patch oauth2-config --project $PROJECT_ID --replace '/urls/login="http://127.0.0.1:4446/login"' --replace '/urls/consent="http://127.0.0.1:4446/consent"'
```
Then run
```sh
ory perform authorization-code --project $PROJECT_ID --client-id xyz --client-secret abc
```
or
```sh
hydra perform authorization-code --client-id xyz --client-secret abc --auth-url http://... --token-url http://...
```

feat: built-in login/consent UI for `hydra perform authorization-code`

---

oauth2/oauth2_auth_code_test.go
persistence/sql/migrations/20241012144910000001_unused_indices.down.sql
persistence/sql/migrations/20241012144910000001_unused_indices.mysql.up.sql
persistence/sql/migrations/20241012144910000001_unused_indices.up.sql

feat: remove unused indices

---

driver/config/provider.go
driver/config/provider_test.go
internal/config/config.yaml
oauth2/fosite_store_helpers.go
oauth2/oauth2_auth_code_test.go
persistence/sql/migratest/migration_test.go
persistence/sql/migrations/20241014121000000000_add_refresh_token_in_grace_period_flag.down.sql
persistence/sql/migrations/20241014121000000000_add_refresh_token_in_grace_period_flag.up.sql
persistence/sql/persister.go
persistence/sql/persister_oauth2.go
spec/config.json
x/fosite_storer.go

Closes https://github.com/ory/hydra/pull/3770
the changes.
works.

feat: graceful refresh token rotation

---

cmd/cmd_perform_authorization_code.go
oauth2/handler.go

This has been supported in Hydra for a while, but was missing from `/.well-known/openid-configuration`.
Also added a flag to `hydra perform authorization-code`: `--response-mode` to test+debug this.

fix: advertise support for response_mode=form_post in OIDC discovery document

---

cmd/server/helper_cert.go
jwk/handler.go
jwk/helper.go
jwk/helper_test.go
jwk/jwt_strategy.go

Using the reproduction steps included in #3863 I'm able to confirm this fixes the read contention:
```zsh
bombardier -d 30s -t 30s -a -c 270 -l http://localhost:4444/.well-known/openid-configuration
Bombarding http://localhost:4444/.well-known/openid-configuration for 30s using 270 connection(s)
[==============================================================================================================================================================] 30s
Done!
Statistics        Avg      Stdev        Max
Reqs/sec      3768.36    2589.36   12964.59
Latency       71.76ms    29.92ms   579.56ms
Latency Distribution
50%    67.30ms
75%    82.45ms
90%    98.98ms
95%   113.15ms
99%   184.51ms
HTTP codes:
1xx - 0, 2xx - 112946, 3xx - 0, 4xx - 0, 5xx - 0
others - 0
Throughput:     7.70MB/s
```
I …

fix: cpu contention on jwk reads + suppress duplicate jwk generation

---

cmd/server/helper_cert.go
jwk/handler.go
jwk/helper.go
jwk/helper_test.go
jwk/jwt_strategy.go

Unfortunately, ory/hydra#3870 introduced a regression in the JWK generation logic.
Reverts ory/hydra#3870

fix: jwk generation incorrectly being skipped

---

go.mod
go.sum
oauth2/oauth2_auth_code_test.go

Resolves a deviation from the OpenID Connect spec, where the `redirect_uri` was not required when performing flows with `scope=openid`.
BREAKING CHANGE: Going forward, OAuth2 Clients requesting an OpenID Connect flow **must** include the `redirect_uri` parameter or the request will be rejected.
the changes.
works.

fix: require `redirect_uri` in openid requests

---

persistence/sql/persister_client.go
persistence/sql/persister_oauth2.go
x/events/events.go

chore: add more tracing context

---

oauth2/.snapshots/TestAuthCodeWithMockStrategy-strategy=jwt-case=0-description=should_pass_request_if_strategy_passes-should_call_refresh_token_hook_if_configured-hook=new.json
oauth2/.snapshots/TestAuthCodeWithMockStrategy-strategy=jwt-case=2-description=should_pass_because_prompt=none_and_max_age_is_less_than_auth_time-should_call_refresh_token_hook_if_configured-hook=new.json
oauth2/.snapshots/TestAuthCodeWithMockStrategy-strategy=jwt-case=5-description=should_pass_with_prompt=login_when_authentication_time_is_recent-should_call_refresh_token_hook_if_configured-hook=new.json
oauth2/.snapshots/TestAuthCodeWithMockStrategy-strategy=opaque-case=0-description=should_pass_request_if_strategy_passes-should_call_refresh_token_hook_if_configured-hook=new.json
oauth2/.snapshots/TestAuthCodeWithMockStrategy-strategy=opaque-case=2-description=should_pass_because_prompt=none_and_max_age_is_less_than_auth_time-should_call_refresh_token_hook_if_configured-hook=new.json
oauth2/.snapshots/TestAuthCodeWithMockStrategy-strategy=opaque-case=5-description=should_pass_with_prompt=login_when_authentication_time_is_recent-should_call_refresh_token_hook_if_configured-hook=new.json
oauth2/token_hook.go

Add requested scopes to the webhook request, allowing the webhook to condition access based on the scopes requested by the user.
Fixes https://github.com/ory/hydra/issues/3620, particularly implementing the idea proposed in this comment: https://github.com/ory/hydra/issues/3620#issuecomment-1745442682.
If this PR is accepted, I can provide an update to the documentation.
the changes.
works.

Include Requested Scopes in Webhook Requests

---

consent/handler.go

chore(docs): add note on idp logout

---

.schema/config.schema.json
client/client.go
internal/config/config.yaml
internal/httpclient/api/openapi.yaml
internal/httpclient/docs/OAuth2Client.md
internal/httpclient/model_o_auth2_client.go
spec/api.json
spec/config.json
spec/swagger.json

The previous link in the documentation led to a page unrelated to JWT.
Updated the URL to https://www.ory.sh/docs/oauth2-oidc/jwt-access-token, which provides proper JWT guidance.
the changes.
works.

fix: JWT documentation link to point to the correct resource

---

client/sdk_test.go
client/validator.go
client/validator_test.go

Contributes to https://github.com/ory-corp/cloud/issues/7395

fix: tos_uri validation

---

client/client.go
internal/httpclient/api/openapi.yaml
internal/httpclient/docs/OAuth2Client.md
internal/httpclient/model_o_auth2_client.go
spec/api.json
spec/swagger.json

This commit addresses several occurrences where 'strategy' was misspelled as 'stragegy' throughout the codebase.
Additionally, a similar issue was found and corrected in the Ory documentation repository (ory/docs), with a corresponding pull request submitted.
Related PR: https://github.com/ory/docs/pull/1966
the changes.
works.

fix: Correct multiple instances of 'stragegy' typo

---

cmd/cmd_create_client.go
cmd/cmd_import_client.go
cmd/cmd_update_client.go

The examples of these three commands are based on hydra v1 cli option.
* `hydra create client`
* `hydra import client`
* `hydra update client`
When I follow the examples using hydra v2 cli, it didn't work. I got the message like `unknown shorthand flag: 'n' in -n`.
I updated these three commands example using v2 option.
```console
$ docker run --rm -it oryd/hydra:v2.3.0 create client --help
...
hydra create oauth2-client -n "my app" -g client_credentials -r token -a core,foobar --keybase keybase_username
...
Examples:
hydra create oauth2-client -n "my app" -c http://localhost/cb -g authorization_code -r code -a core,foobar
$ docker run --rm -it oryd/hydra:v2.3.0 create oauth2-client -n "my app" -c http://localhost/cb -g authorization_code -r code -a core,foobar
Error: unknown shorthand …
```

fix: client command example using v2 option

---

client/sdk_test.go
client/validator.go
client/validator_test.go

The validator rejects updates when `JSONWebKeysURI` is non-empty and `JSONWebKeys` is not nil, but this field is set to `new(x.JoseJSONWebKeySet)` in Client's `BeforeSave`.
#3935 
the changes.
works.

fix: allow updating when JWKS URI is set (#3935)

---

oauth2/.snapshots/TestHandlerOauthAuthorizationServer-hsm_enabled=false.json
oauth2/.snapshots/TestHandlerOauthAuthorizationServer-hsm_enabled=true.json
oauth2/handler.go
oauth2/handler_test.go

In order to support OAuth2.1 and some specific integrations that leverage the `/.well-known/oauth-authorization-server` endpoint, this PR adds a handler for the specific endpoint. The `/.well-known/openid-configuration` endpoint already supports all configuration items that conform to this endpoint as seen here: https://datatracker.ietf.org/doc/html/rfc8414

feat: add handler for /.well-known/oauth-authorization-server.
